"""Генератор шаблона проверки серверного помещения и сервера.

Запуск (из корня проекта):

    python tools/build_server_template.py

Нормативная основа — приказ ФСТЭК России от 11.02.2013 № 17 «Об утверждении
Требований о защите информации, не составляющей государственную тайну,
содержащейся в государственных информационных системах» (ред. от 28.08.2024);
СП 484.1311500.2020 «Системы противопожарной защиты. Системы пожарной
сигнализации и автоматизация систем противопожарной защиты» (приказ МЧС
России от 31.07.2020 № 582, ред. от 27.03.2025); приказы ФСТЭК России
№ 21 и № 239; серия ГОСТ Р ИСО/МЭК 27000; ГОСТ Р 51275-2006;
ГОСТ Р 53245-2008; СанПиН 1.2.3685-21; ГОСТ Р 51241-2008;
ГОСТ Р 51558-2014.

Разделение «проверено по открытым источникам» и «требует сверки» сделано в
docs/normative-base.md: в этой сессии подтверждены приказ № 17 и
СП 484.1311500.2020, остальные документы приведены по общеизвестной практике.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "server_bezopasnost.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
YESNO = ("Да", "Нет")
ASSESSMENT = (
    "Исправно",
    "Работоспособно",
    "Ограниченно работоспособно",
    "Не работоспособно",
)
PERMISSION = ("Допускается", "Допускается с ограничениями", "Не допускается")

FSTEK17 = "Приказ ФСТЭК России от 11.02.2013 № 17"
SP484 = "СП 484.1311500.2020"

GROUPS = [
    "Общие сведения",
    "Документация и организация",
    "Доступ в серверное помещение",
    "Пожарная безопасность",
    "Электропитание и бесперебойность",
    "Микроклимат и кабельное хозяйство",
    "Учётные записи и пароли",
    "Обновления и защита от вредоносного кода",
    "Резервное копирование и журналирование",
    "Заключение",
]

FIELDS: list[FieldSpec] = [
    # ---------------------------------------------------- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Подразделение и серверное помещение",
    ),
    FieldSpec(
        name="server_room",
        label="Серверное помещение (номер, расположение)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Помещение 312, корпус А, 3 этаж",
    ),
    FieldSpec(
        name="server_count",
        label="Количество серверов в помещении",
        type="number",
        group="Общие сведения",
        required=True,
        unit="шт.",
    ),
    FieldSpec(
        name="server_purpose",
        label="Назначение серверов и обрабатываемая информация",
        type="textarea",
        group="Общие сведения",
        required=True,
        placeholder="Какие системы работают и какая информация обрабатывается",
        description=f"{FSTEK17} — от категории информации зависят требования",
    ),
    FieldSpec(
        name="information_category",
        label="Категория обрабатываемой информации",
        type="text",
        group="Общие сведения",
        placeholder="Персональные данные, коммерческая тайна, общедоступная",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
    ),
    FieldSpec(
        name="inspector",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Инженер по защите информации",
    ),
    FieldSpec(
        name="normative_base",
        label="Нормативная база проверки",
        type="textarea",
        group="Общие сведения",
        placeholder="Приказы ФСТЭК № 17 и № 21, СП 484.1311500.2020",
    ),
    # --------------------------------------------- Документация и организация
    FieldSpec(
        name="access_policy",
        label="Утверждён перечень лиц с правом доступа в серверное помещение",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
        description=f"{FSTEK17}, раздел о защите от несанкционированного доступа",
    ),
    FieldSpec(
        name="server_regulations",
        label="Имеется инструкция по эксплуатации серверного помещения и серверов",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="responsible_appointed",
        label="Приказом назначен ответственный за серверное оборудование",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="information_system_list",
        label="Ведётся перечень информационных систем и обрабатываемых данных",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="hardware_inventory",
        label="Ведётся учёт оборудования: модели, серийные номера, расположение",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="software_licensed",
        label="Используемое программное обеспечение лицензионно и учтено",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="access_journal",
        label="Ведётся журнал учёта посещений серверного помещения",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=YESNO,
    ),
    FieldSpec(
        name="media_journal",
        label="Ведётся журнал учёта съёмных носителей информации",
        type="dropdown",
        group="Документация и организация",
        options=YESNO,
        description="ГОСТ Р ИСО/МЭК 27002 — контроль носителей",
    ),
    FieldSpec(
        name="staff_briefed",
        label="Работники ознакомлены с требованиями по защите информации под подпись",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="cleanup_regulations",
        label="Утверждён порядок уничтожения информации с носителей при списании",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    # ------------------------------------------- Доступ в серверное помещение
    FieldSpec(
        name="room_locked",
        label="Помещение запирается, ключи выдаются под подпись",
        type="dropdown",
        group="Доступ в серверное помещение",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="access_system_present",
        label="Установлена система контроля и управления доступом",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=VERDICT,
        description="ГОСТ Р 51241-2008",
    ),
    FieldSpec(
        name="access_log_depth",
        label="Глубина хранения журнала проходов системы доступа",
        type="number",
        group="Доступ в серверное помещение",
        unit="суток",
        placeholder="Не менее срока, установленного политикой",
    ),
    FieldSpec(
        name="access_rights_actual",
        label="Права доступа в помещение соответствуют утверждённому перечню",
        type="dropdown",
        group="Доступ в серверное помещение",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="dismissed_revoked",
        label="Права доступа уволенных работников отозваны",
        type="dropdown",
        group="Доступ в серверное помещение",
        required=True,
        options=VERDICT,
        description="Типичное нарушение при проверках",
    ),
    FieldSpec(
        name="windows_secured",
        label="Оконные проёмы защищены от проникновения или отсутствуют",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_present",
        label="Ведётся видеонаблюдение за входом в помещение",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=VERDICT,
        description="ГОСТ Р 51558-2014",
    ),
    FieldSpec(
        name="cctv_archive_depth",
        label="Глубина архива видеонаблюдения",
        type="number",
        group="Доступ в серверное помещение",
        unit="суток",
    ),
    FieldSpec(
        name="alarm_system",
        label="Помещение оборудовано охранной сигнализацией, исправна",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=STATE,
    ),
    FieldSpec(
        name="visitors_escorted",
        label="Посетители находятся в помещении только в сопровождении",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=VERDICT,
    ),
    FieldSpec(
        name="keys_control",
        label="Учёт выдачи ключей и электронных карт ведётся",
        type="dropdown",
        group="Доступ в серверное помещение",
        options=VERDICT,
    ),
    # ------------------------------------------------- Пожарная безопасность
    FieldSpec(
        name="fire_alarm_present",
        label="Помещение оборудовано автоматической пожарной сигнализацией",
        type="dropdown",
        group="Пожарная безопасность",
        required=True,
        options=VERDICT,
        description=f"{SP484}",
    ),
    FieldSpec(
        name="fire_alarm_works",
        label="Пожарная сигнализация исправна, проверка проведена",
        type="dropdown",
        group="Пожарная безопасность",
        required=True,
        options=STATE,
        description=f"{SP484} — требуется периодическая проверка работоспособности",
    ),
    FieldSpec(
        name="fire_alarm_date",
        label="Дата последней проверки пожарной сигнализации",
        type="date",
        group="Пожарная безопасность",
    ),
    FieldSpec(
        name="extinguishing_present",
        label="Установлена автоматическая установка пожаротушения",
        type="dropdown",
        group="Пожарная безопасность",
        options=VERDICT,
        description="Для серверных применяется газовое пожаротушение",
    ),
    FieldSpec(
        name="extinguishing_agent",
        label="Тип огнетушащего вещества",
        type="text",
        group="Пожарная безопасность",
        placeholder="Хладон, СО2, азот",
        description="Порошковые и водные установки для серверных не применяются",
    ),
    FieldSpec(
        name="extinguishing_works",
        label="Установка пожаротушения исправна, баллоны заряжены и в сроке",
        type="dropdown",
        group="Пожарная безопасность",
        options=STATE,
    ),
    FieldSpec(
        name="extinguisher_present",
        label="Переносные огнетушители в наличии, срок годности не истёк",
        type="dropdown",
        group="Пожарная безопасность",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="smoke_sensors_clear",
        label="Датчики не загорожены оборудованием и не загрязнены",
        type="dropdown",
        group="Пожарная безопасность",
        options=VERDICT,
    ),
    FieldSpec(
        name="flammable_absent",
        label="В помещении отсутствуют горючие материалы и посторонние предметы",
        type="dropdown",
        group="Пожарная безопасность",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="fire_evacuation_plan",
        label="Схема эвакуации и знаки безопасности размещены",
        type="dropdown",
        group="Пожарная безопасность",
        options=VERDICT,
    ),
    FieldSpec(
        name="fire_doors_ok",
        label="Противопожарные двери и проходы свободны, закрываются",
        type="dropdown",
        group="Пожарная безопасность",
        options=STATE,
    ),
    # ------------------------------------------- Электропитание и бесперебойность
    FieldSpec(
        name="ups_present",
        label="Серверы подключены через источник бесперебойного питания",
        type="dropdown",
        group="Электропитание и бесперебойность",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="ups_battery_ok",
        label="Аккумуляторные батареи ИБП в норме, срок службы не истёк",
        type="dropdown",
        group="Электропитание и бесперебойность",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="ups_test_date",
        label="Дата последнего теста ИБП под нагрузкой",
        type="date",
        group="Электропитание и бесперебойность",
    ),
    FieldSpec(
        name="backup_runtime",
        label="Время автономной работы ИБП под нагрузкой",
        type="number",
        group="Электропитание и бесперебойность",
        unit="мин",
        required=True,
    ),
    FieldSpec(
        name="second_source",
        label="Имеется второй независимый ввод электроснабжения",
        type="dropdown",
        group="Электропитание и бесперебойность",
        options=VERDICT,
    ),
    FieldSpec(
        name="grounding_ok",
        label="Заземление и защитное зануление выполнены, сопротивление измерено",
        type="dropdown",
        group="Электропитание и бесперебойность",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="grounding_value",
        label="Сопротивление заземления по последнему измерению",
        type="number",
        group="Электропитание и бесперебойность",
        unit="Ом",
    ),
    FieldSpec(
        name="grounding_date",
        label="Дата последнего измерения сопротивления заземления",
        type="date",
        group="Электропитание и бесперебойность",
    ),
    FieldSpec(
        name="protection_devices",
        label="Устройства защиты от перегрузки и короткого замыкания исправны",
        type="dropdown",
        group="Электропитание и бесперебойность",
        options=STATE,
    ),
    FieldSpec(
        name="protection_test_date",
        label="Дата последней проверки устройств защиты",
        type="date",
        group="Электропитание и бесперебойность",
    ),
    FieldSpec(
        name="cable_condition",
        label="Силовые кабели без повреждений изоляции и следов перегрева",
        type="dropdown",
        group="Электропитание и бесперебойность",
        options=STATE,
    ),
    FieldSpec(
        name="power_off_available",
        label="Есть возможность аварийного обесточивания помещения",
        type="dropdown",
        group="Электропитание и бесперебойность",
        options=VERDICT,
    ),
    # ------------------------------------------ Микроклимат и кабельное хозяйство
    FieldSpec(
        name="temperature",
        label="Температура воздуха в помещении",
        type="number",
        group="Микроклимат и кабельное хозяйство",
        required=True,
        unit="°C",
        placeholder="18–27 по рекомендациям производителя",
        description="СанПиН 1.2.3685-21 — гигиенические нормативы",
    ),
    FieldSpec(
        name="humidity",
        label="Относительная влажность воздуха",
        type="number",
        group="Микроклимат и кабельное хозяйство",
        unit="%",
        placeholder="40–60",
    ),
    FieldSpec(
        name="air_conditioning",
        label="Кондиционирование работоспособно, резервный кондиционер имеется",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="ventilation_ok",
        label="Приточно-вытяжная вентиляция работоспособна",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=STATE,
    ),
    FieldSpec(
        name="microclimate_monitoring",
        label="Температура и влажность контролируются автоматически",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=VERDICT,
    ),
    FieldSpec(
        name="leaks_absent",
        label="Следы протечек, конденсата и трубопроводы над оборудованием отсутствуют",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="racks_secured",
        label="Стойки и шкафы закреплены, устойчивы, не перегружены",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=STATE,
    ),
    FieldSpec(
        name="cable_organized",
        label="Кабели уложены упорядоченно и промаркированы с двух сторон",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        required=True,
        options=VERDICT,
        description="ГОСТ Р 53245-2008 — структурированные кабельные системы",
    ),
    FieldSpec(
        name="cable_journals",
        label="Ведётся журнал кабельных соединений и коммутации",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_no_stress",
        label="Кабели не имеют натяжения, изломов и повреждений изоляции",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=STATE,
    ),
    FieldSpec(
        name="cleanliness_ok",
        label="Помещение содержится в чистоте, пыль на оборудовании отсутствует",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=VERDICT,
    ),
    FieldSpec(
        name="lighting_ok",
        label="Освещение рабочей зоны достаточно, аварийное освещение имеется",
        type="dropdown",
        group="Микроклимат и кабельное хозяйство",
        options=STATE,
    ),
    # ------------------------------------------------ Учётные записи и пароли
    FieldSpec(
        name="password_policy",
        label="Утверждена политика паролей: длина, сложность, срок действия",
        type="dropdown",
        group="Учётные записи и пароли",
        required=True,
        options=VERDICT,
        description=f"{FSTEK17} — требования к идентификации и аутентификации",
    ),
    FieldSpec(
        name="password_min_length",
        label="Минимальная длина пароля по политике",
        type="number",
        group="Учётные записи и пароли",
        unit="символов",
        placeholder="Не менее 8, рекомендуется 12",
    ),
    FieldSpec(
        name="default_passwords_changed",
        label="Пароли по умолчанию на оборудовании и службах изменены",
        type="dropdown",
        group="Учётные записи и пароли",
        required=True,
        options=VERDICT,
        description="Типичное нарушение при проверках",
    ),
    FieldSpec(
        name="admin_accounts_limited",
        label="Число учётных записей с правами администратора ограничено",
        type="dropdown",
        group="Учётные записи и пароли",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="shared_accounts_absent",
        label="Общие и групповые учётные записи не используются",
        type="dropdown",
        group="Учётные записи и пароли",
        options=VERDICT,
    ),
    FieldSpec(
        name="stale_accounts_removed",
        label="Неиспользуемые и уволенных сотрудников учётные записи удалены",
        type="dropdown",
        group="Учётные записи и пароли",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="mfa_used",
        label="Для удалённого доступа применяется двухфакторная аутентификация",
        type="dropdown",
        group="Учётные записи и пароли",
        options=VERDICT,
        description="Обязательна для доступа из внешних сетей",
    ),
    FieldSpec(
        name="remote_access_limited",
        label="Удалённый доступ администраторов ограничен по адресам и каналам",
        type="dropdown",
        group="Учётные записи и пароли",
        options=VERDICT,
    ),
    FieldSpec(
        name="local_login_restricted",
        label="Интерактивный вход на серверы ограничен необходимыми лицами",
        type="dropdown",
        group="Учётные записи и пароли",
        options=VERDICT,
    ),
    FieldSpec(
        name="screen_lock",
        label="Блокировка сеанса при бездействии настроена",
        type="dropdown",
        group="Учётные записи и пароли",
        options=VERDICT,
    ),
    FieldSpec(
        name="passwords_stored_safely",
        label="Пароли не хранятся в открытом виде в файлах и скриптах",
        type="dropdown",
        group="Учётные записи и пароли",
        required=True,
        options=VERDICT,
    ),
    # ---------------------------------- Обновления и защита от вредоносного кода
    FieldSpec(
        name="os_supported",
        label="Версии операционных систем поддерживаются производителем",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="updates_installed",
        label="Обновления безопасности установлены в установленные сроки",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="last_update_date",
        label="Дата последней установки обновлений безопасности",
        type="date",
        group="Обновления и защита от вредоносного кода",
    ),
    FieldSpec(
        name="update_process",
        label="Утверждён порядок установки обновлений с проверкой на тестовом стенде",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        options=VERDICT,
    ),
    FieldSpec(
        name="antivirus_present",
        label="Средства антивирусной защиты установлены на всех серверах",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="antivirus_updated",
        label="Базы антивирусной защиты обновляются автоматически",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        options=VERDICT,
    ),
    FieldSpec(
        name="antivirus_scan_date",
        label="Дата последней полной проверки на вредоносный код",
        type="date",
        group="Обновления и защита от вредоносного кода",
    ),
    FieldSpec(
        name="unused_services_off",
        label="Неиспользуемые службы, порты и учётные записи отключены",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="firewall_configured",
        label="Межсетевое экранирование настроено, правила актуальны",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        options=VERDICT,
    ),
    FieldSpec(
        name="vulnerability_scan_date",
        label="Дата последнего сканирования на уязвимости",
        type="date",
        group="Обновления и защита от вредоносного кода",
    ),
    FieldSpec(
        name="critical_vulnerabilities",
        label="Критические уязвимости, выявленные сканированием, устранены",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        options=VERDICT,
    ),
    FieldSpec(
        name="removable_media_blocked",
        label="Использование съёмных носителей ограничено техническими средствами",
        type="dropdown",
        group="Обновления и защита от вредоносного кода",
        options=VERDICT,
    ),
    # ------------------------------- Резервное копирование и журналирование
    FieldSpec(
        name="backup_present",
        label="Резервное копирование выполняется по утверждённому регламенту",
        type="dropdown",
        group="Резервное копирование и журналирование",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="backup_frequency",
        label="Периодичность резервного копирования",
        type="text",
        group="Резервное копирование и журналирование",
        placeholder="Ежедневно, полная копия еженедельно",
    ),
    FieldSpec(
        name="backup_last_date",
        label="Дата последней успешной резервной копии",
        type="date",
        group="Резервное копирование и журналирование",
        required=True,
    ),
    FieldSpec(
        name="backup_offsite",
        label="Копии хранятся вне серверного помещения",
        type="dropdown",
        group="Резервное копирование и журналирование",
        required=True,
        options=VERDICT,
        description="Копия в том же помещении не защищает от пожара и затопления",
    ),
    FieldSpec(
        name="backup_restore_tested",
        label="Восстановление из копии проверялось, акт имеется",
        type="dropdown",
        group="Резервное копирование и журналирование",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="backup_restore_date",
        label="Дата последней проверки восстановления",
        type="date",
        group="Резервное копирование и журналирование",
    ),
    FieldSpec(
        name="backup_encrypted",
        label="Резервные копии шифруются при хранении и передаче",
        type="dropdown",
        group="Резервное копирование и журналирование",
        options=VERDICT,
    ),
    FieldSpec(
        name="backup_access_limited",
        label="Доступ к резервным копиям ограничен",
        type="dropdown",
        group="Резервное копирование и журналирование",
        options=VERDICT,
    ),
    FieldSpec(
        name="event_logging_on",
        label="Журналирование событий безопасности включено на серверах",
        type="dropdown",
        group="Резервное копирование и журналирование",
        required=True,
        options=VERDICT,
        description=f"{FSTEK17} — регистрация событий безопасности",
    ),
    FieldSpec(
        name="log_depth",
        label="Глубина хранения журналов событий",
        type="number",
        group="Резервное копирование и журналирование",
        unit="месяцев",
    ),
    FieldSpec(
        name="logs_protected",
        label="Журналы защищены от изменения и удаления пользователями",
        type="dropdown",
        group="Резервное копирование и журналирование",
        options=VERDICT,
    ),
    FieldSpec(
        name="time_sync",
        label="Синхронизация времени настроена на всех серверах",
        type="dropdown",
        group="Резервное копирование и журналирование",
        required=True,
        options=VERDICT,
        description="Без единого времени журналы разных серверов несопоставимы",
    ),
    FieldSpec(
        name="monitoring_present",
        label="Ведётся мониторинг доступности и ресурсов серверов",
        type="dropdown",
        group="Резервное копирование и журналирование",
        options=VERDICT,
    ),
    FieldSpec(
        name="incidents_registered",
        label="Инциденты информационной безопасности регистрируются и разбираются",
        type="dropdown",
        group="Резервное копирование и журналирование",
        options=VERDICT,
    ),
    # ------------------------------------------------------------ Заключение
    FieldSpec(
        name="security_assessment",
        label="Оценка состояния защиты серверного помещения и серверов",
        type="dropdown",
        group="Заключение",
        required=True,
        options=ASSESSMENT,
    ),
    FieldSpec(
        name="defects_found",
        label="Выявленные несоответствия и замечания",
        type="textarea",
        group="Заключение",
        placeholder="Перечень или «не выявлено»",
    ),
    FieldSpec(
        name="defects_critical",
        label="Несоответствия, требующие немедленного устранения",
        type="textarea",
        group="Заключение",
        placeholder="Перечень или «не выявлено»",
    ),
    FieldSpec(
        name="repair_deadline",
        label="Срок устранения выявленных замечаний",
        type="date",
        group="Заключение",
    ),
    FieldSpec(
        name="operation_permission",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=PERMISSION,
    ),
    FieldSpec(
        name="conclusion",
        label="Вывод по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Краткий вывод",
    ),
]


if __name__ == "__main__":
    build_template(OUTPUT, GROUPS, FIELDS)
