"""Генератор шаблона проверки технических средств охраны (ТСО).

Запуск (из корня проекта):

    python tools/build_security_template.py

Нормативная основа — Федеральный закон от 21.07.2011 № 256-ФЗ «О безопасности
объектов топливно-энергетического комплекса», постановление Правительства РФ
от 05.05.2012 № 458, РД 78.36.003-2002/МВД России, ГОСТ Р 51558-2014,
ГОСТ Р 51241-2008, ГОСТ Р 52435-2015.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "tehnicheskie_sredstva_ohrany.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
DONE = ("Выполнено", "Не выполнено", "Не требуется")
AVAIL = ("В наличии", "Отсутствует", "Частично")
YESNO = ("Да", "Нет")
ASSESSMENT = (
    "Исправно",
    "Работоспособно",
    "Ограниченно работоспособно",
    "Не работоспособно",
)
PERMISSION = ("Допускается", "Допускается с ограничениями", "Не допускается")

GROUPS = [
    "Общие сведения",
    "Документация и организация",
    "Инженерно-техническая укреплённость",
    "Охранная и тревожная сигнализация",
    "Охранное телевидение",
    "Контроль и управление доступом",
    "Периметровые средства обнаружения",
    "Электропитание и линии связи",
    "Проверка работоспособности",
    "Заключение",
]

FIELDS: list[FieldSpec] = [
    # --- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="ПАО «Газпром», ЛПУМГ, КС, крановый узел",
        description="Организация и охраняемый объект",
    ),
    FieldSpec(
        name="hazard_level",
        label="Уровень опасности объекта по ФЗ-256",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Высокий уровень опасности",
            "Средний уровень опасности",
            "Низкий уровень опасности",
            "Не категорирован",
        ),
        description="ФЗ от 21.07.2011 № 256-ФЗ, постановление Правительства РФ № 458",
    ),
    FieldSpec(
        name="security_type",
        label="Вид охраны объекта",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Войсковая",
            "Полицейская",
            "Ведомственная",
            "Частная охранная организация",
            "Техническая без поста охраны",
        ),
        description="Определяет требования к системе физической защиты",
    ),
    FieldSpec(
        name="tso_composition",
        label="Состав технических средств охраны",
        type="textarea",
        group="Общие сведения",
        required=True,
        placeholder="ОС, СОТ, СКУД, периметровые средства",
        description="Перечень подсистем, установленных на объекте",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
    ),
    FieldSpec(
        name="inspection_type",
        label="Вид проверки",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Плановое обследование",
            "Внеплановое обследование",
            "Техническое обслуживание",
            "Проверка работоспособности",
            "После ремонта",
            "Комиссионная проверка",
        ),
    ),
    FieldSpec(
        name="executor",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Сидоров С.С., инженер ТСО",
        description="Лицо, проводившее проверку",
    ),
    FieldSpec(
        name="outdoor_temp",
        label="Температура наружного воздуха",
        type="number",
        group="Общие сведения",
        placeholder="12",
        unit="°C",
    ),
    FieldSpec(
        name="regulatory_basis",
        label="Нормативная база проверки",
        type="text",
        group="Общие сведения",
        placeholder="ФЗ-256, ПП РФ № 458, РД 78.36.003-2002",
    ),
    # --- Документация и организация
    FieldSpec(
        name="docs_project",
        label="Проектная документация на ТСО",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=AVAIL,
        description="РД 78.36.003-2002, требования к проектированию",
    ),
    FieldSpec(
        name="docs_passports",
        label="Паспорта и формуляры на средства ТСО",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=AVAIL,
    ),
    FieldSpec(
        name="docs_schemes",
        label="Структурные схемы и схемы подключения",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=AVAIL,
    ),
    FieldSpec(
        name="docs_actual",
        label="Документация соответствует фактическому исполнению",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="safety_passport",
        label="Паспорт безопасности объекта ТЭК",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=AVAIL,
        description="ФЗ от 21.07.2011 № 256-ФЗ, статья 8",
    ),
    FieldSpec(
        name="category_act",
        label="Акт категорирования объекта",
        type="dropdown",
        group="Документация и организация",
        options=AVAIL,
        description="Постановление Правительства РФ от 05.05.2012 № 458",
    ),
    FieldSpec(
        name="service_contract",
        label="Договор на техническое обслуживание ТСО",
        type="dropdown",
        group="Документация и организация",
        options=AVAIL,
    ),
    FieldSpec(
        name="responsible_person",
        label="Ответственный за эксплуатацию ТСО назначен",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="staff_instructed",
        label="Персонал проинструктирован по действиям при тревоге",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="to_schedule",
        label="График технического обслуживания утверждён",
        type="dropdown",
        group="Документация и организация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="to_journal",
        label="Журнал технического обслуживания и ремонтов ведётся",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="alarm_log",
        label="Журнал срабатываний и тревог ведётся",
        type="dropdown",
        group="Документация и организация",
        options=VERDICT,
    ),
    FieldSpec(
        name="previous_acts",
        label="Акты предыдущих обследований и предписания",
        type="dropdown",
        group="Документация и организация",
        options=AVAIL,
    ),
    # --- Инженерно-техническая укреплённость
    FieldSpec(
        name="fence_condition",
        label="Ограждение периметра",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        required=True,
        options=STATE,
        description="РД 78.36.003-2002, требования к укреплённости",
    ),
    FieldSpec(
        name="fence_height",
        label="Высота ограждения",
        type="number",
        group="Инженерно-техническая укреплённость",
        placeholder="2,5",
        unit="м",
    ),
    FieldSpec(
        name="fence_integrity",
        label="Целостность ограждения, отсутствие проломов и подкопов",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="gates_condition",
        label="Ворота и калитки",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="gates_locking",
        label="Запирающие устройства ворот и калиток",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=VERDICT,
    ),
    FieldSpec(
        name="additional_barriers",
        label="Дополнительные инженерные средства защиты",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=VERDICT,
        description="Козырьки, спиральные барьеры, колючая проволока",
    ),
    FieldSpec(
        name="doors_condition",
        label="Входные двери и дверные проёмы",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=STATE,
    ),
    FieldSpec(
        name="windows_condition",
        label="Оконные проёмы и защитные решётки",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=STATE,
    ),
    FieldSpec(
        name="locks_class",
        label="Класс замков и запирающих устройств",
        type="text",
        group="Инженерно-техническая укреплённость",
        placeholder="IV класс по ГОСТ 5089",
        description="РД 78.36.003-2002, классы устойчивости",
    ),
    FieldSpec(
        name="tso_room",
        label="Помещение для размещения ТСО",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=VERDICT,
    ),
    FieldSpec(
        name="perimeter_lighting",
        label="Освещение периметра и подходов",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=VERDICT,
    ),
    FieldSpec(
        name="warning_signs",
        label="Предупредительные знаки и таблички",
        type="dropdown",
        group="Инженерно-техническая укреплённость",
        options=VERDICT,
    ),
    # --- Охранная и тревожная сигнализация
    FieldSpec(
        name="alarm_present",
        label="Охранная и тревожная сигнализация",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=STATE,
        description="ГОСТ Р 52435-2015, технические средства охранной сигнализации",
    ),
    FieldSpec(
        name="alarm_zones",
        label="Количество шлейфов и зон",
        type="number",
        group="Охранная и тревожная сигнализация",
        placeholder="12",
        unit="шт",
    ),
    FieldSpec(
        name="alarm_detectors",
        label="Извещатели: типы, количество, места установки",
        type="textarea",
        group="Охранная и тревожная сигнализация",
        placeholder="СМК, ИК, магнитоконтактные",
        description="Перечень по проекту",
    ),
    FieldSpec(
        name="alarm_detectors_state",
        label="Состояние извещателей",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="alarm_coverage",
        label="Зоны обнаружения перекрывают уязвимые места",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=VERDICT,
        description="Отсутствие «мёртвых» зон и обходных путей",
    ),
    FieldSpec(
        name="alarm_loops",
        label="Шлейфы исправны, сопротивление в норме",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="alarm_panel",
        label="Прибор приёмно-контрольный",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="alarm_keypads",
        label="Клавиатуры и считыватели кода",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        options=STATE,
    ),
    FieldSpec(
        name="alarm_sirens",
        label="Звуковые и световые оповещатели",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="alarm_tamper",
        label="Защита от вскрытия корпусов и линий",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        options=VERDICT,
    ),
    FieldSpec(
        name="alarm_transmission",
        label="Канал передачи тревог на пульт",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="alarm_backup_channel",
        label="Резервный канал передачи тревог",
        type="dropdown",
        group="Охранная и тревожная сигнализация",
        options=VERDICT,
    ),
    FieldSpec(
        name="alarm_response_time",
        label="Время доставки тревожного извещения",
        type="number",
        group="Охранная и тревожная сигнализация",
        placeholder="10",
        unit="с",
    ),
    FieldSpec(
        name="alarm_test_date",
        label="Дата последней проверки сигнализации",
        type="date",
        group="Охранная и тревожная сигнализация",
    ),
    # --- Охранное телевидение
    FieldSpec(
        name="cctv_present",
        label="Система охранного телевидения",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=STATE,
        description="ГОСТ Р 51558-2014, системы охранные телевизионные",
    ),
    FieldSpec(
        name="cctv_cameras",
        label="Количество видеокамер",
        type="number",
        group="Охранное телевидение",
        placeholder="16",
        unit="шт",
    ),
    FieldSpec(
        name="cctv_cameras_state",
        label="Состояние камер, юстировка и фокус",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="cctv_coverage",
        label="Зоны обзора соответствуют проекту",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_image_quality",
        label="Качество изображения достаточно для идентификации",
        type="dropdown",
        group="Охранное телевидение",
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_night_mode",
        label="Работа в ночное время и ИК-подсветка",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_recorder",
        label="Видеорегистратор и накопители",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="cctv_recording",
        label="Запись ведётся по всем каналам",
        type="dropdown",
        group="Охранное телевидение",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_archive_depth",
        label="Глубина видеоархива",
        type="number",
        group="Охранное телевидение",
        placeholder="30",
        unit="сут",
    ),
    FieldSpec(
        name="cctv_archive_norm",
        label="Глубина архива соответствует требованиям",
        type="dropdown",
        group="Охранное телевидение",
        options=VERDICT,
    ),
    FieldSpec(
        name="cctv_time_sync",
        label="Точность времени на записи",
        type="dropdown",
        group="Охранное телевидение",
        options=VERDICT,
        description="Расхождение времени затрудняет разбор событий",
    ),
    FieldSpec(
        name="cctv_monitors",
        label="Видеомониторы и видеостена",
        type="dropdown",
        group="Охранное телевидение",
        options=STATE,
    ),
    FieldSpec(
        name="cctv_access",
        label="Пароли изменены, доступ к системе ограничен",
        type="dropdown",
        group="Охранное телевидение",
        options=VERDICT,
    ),
    # --- Контроль и управление доступом
    FieldSpec(
        name="acs_present",
        label="Система контроля и управления доступом",
        type="dropdown",
        group="Контроль и управление доступом",
        required=True,
        options=STATE,
        description="ГОСТ Р 51241-2008, средства и системы контроля доступа",
    ),
    FieldSpec(
        name="acs_controllers",
        label="Контроллеры СКУД",
        type="dropdown",
        group="Контроль и управление доступом",
        options=STATE,
    ),
    FieldSpec(
        name="acs_readers",
        label="Считыватели идентификаторов",
        type="dropdown",
        group="Контроль и управление доступом",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="acs_locks",
        label="Электромеханические замки и защёлки",
        type="dropdown",
        group="Контроль и управление доступом",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="acs_identifiers",
        label="Идентификаторы: типы и количество",
        type="textarea",
        group="Контроль и управление доступом",
        placeholder="Карты Mifare, брелоки",
    ),
    FieldSpec(
        name="acs_access_levels",
        label="Уровни доступа настроены по регламенту",
        type="dropdown",
        group="Контроль и управление доступом",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="acs_antipassback",
        label="Защита от повторного прохода",
        type="dropdown",
        group="Контроль и управление доступом",
        options=VERDICT,
    ),
    FieldSpec(
        name="acs_turnstile",
        label="Турникет или шлюз",
        type="dropdown",
        group="Контроль и управление доступом",
        options=STATE,
    ),
    FieldSpec(
        name="acs_emergency_release",
        label="Разблокировка при пожаре или аварии",
        type="dropdown",
        group="Контроль и управление доступом",
        required=True,
        options=VERDICT,
        description="Свободная эвакуация людей при срабатывании АПС",
    ),
    FieldSpec(
        name="acs_logs",
        label="Протоколы событий доступа ведутся",
        type="dropdown",
        group="Контроль и управление доступом",
        options=VERDICT,
    ),
    FieldSpec(
        name="acs_log_depth",
        label="Глубина хранения протокола доступа",
        type="number",
        group="Контроль и управление доступом",
        placeholder="90",
        unit="сут",
    ),
    FieldSpec(
        name="acs_time_sync",
        label="Синхронизация времени в СКУД",
        type="dropdown",
        group="Контроль и управление доступом",
        options=VERDICT,
    ),
    # --- Периметровые средства обнаружения
    FieldSpec(
        name="perimeter_sensors",
        label="Периметровые средства обнаружения",
        type="dropdown",
        group="Периметровые средства обнаружения",
        options=STATE,
    ),
    FieldSpec(
        name="perimeter_zones",
        label="Количество зон обнаружения периметра",
        type="number",
        group="Периметровые средства обнаружения",
        placeholder="6",
        unit="шт",
    ),
    FieldSpec(
        name="perimeter_coverage",
        label="Зоны обнаружения перекрывают весь периметр",
        type="dropdown",
        group="Периметровые средства обнаружения",
        options=VERDICT,
    ),
    FieldSpec(
        name="perimeter_power",
        label="Питание периметровых средств",
        type="dropdown",
        group="Периметровые средства обнаружения",
        options=STATE,
    ),
    FieldSpec(
        name="perimeter_cables",
        label="Кабельные линии периметровых средств",
        type="dropdown",
        group="Периметровые средства обнаружения",
        options=STATE,
    ),
    FieldSpec(
        name="perimeter_false_alarms",
        label="Ложные срабатывания за межпроверочный период",
        type="dropdown",
        group="Периметровые средства обнаружения",
        options=VERDICT,
    ),
    # --- Электропитание и линии связи
    FieldSpec(
        name="power_main",
        label="Основное электропитание ТСО",
        type="dropdown",
        group="Электропитание и линии связи",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="power_backup",
        label="Резервное электропитание (аккумуляторы, ИБП)",
        type="dropdown",
        group="Электропитание и линии связи",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="battery_voltage",
        label="Напряжение аккумуляторных батарей",
        type="number",
        group="Электропитание и линии связи",
        placeholder="13,2",
        unit="В",
    ),
    FieldSpec(
        name="battery_test",
        label="Аккумуляторы проверены под нагрузкой",
        type="dropdown",
        group="Электропитание и линии связи",
        options=DONE,
    ),
    FieldSpec(
        name="battery_install_date",
        label="Дата установки аккумуляторных батарей",
        type="date",
        group="Электропитание и линии связи",
    ),
    FieldSpec(
        name="backup_runtime",
        label="Время работы от резервного источника",
        type="number",
        group="Электропитание и линии связи",
        placeholder="24",
        unit="ч",
    ),
    FieldSpec(
        name="backup_runtime_norm",
        label="Время работы от резерва соответствует требованиям",
        type="dropdown",
        group="Электропитание и линии связи",
        options=VERDICT,
    ),
    FieldSpec(
        name="cables_condition",
        label="Состояние кабельных линий ТСО",
        type="dropdown",
        group="Электропитание и линии связи",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="cables_marking",
        label="Маркировка кабелей и клеммных соединений",
        type="dropdown",
        group="Электропитание и линии связи",
        options=VERDICT,
    ),
    FieldSpec(
        name="cables_sealing",
        label="Вводы и уплотнения кабелей",
        type="dropdown",
        group="Электропитание и линии связи",
        options=VERDICT,
    ),
    FieldSpec(
        name="grounding_tso",
        label="Заземление оборудования ТСО",
        type="dropdown",
        group="Электропитание и линии связи",
        required=True,
        options=VERDICT,
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="surge_protection",
        label="Защита линий от импульсных перенапряжений",
        type="dropdown",
        group="Электропитание и линии связи",
        options=VERDICT,
    ),
    # --- Проверка работоспособности
    FieldSpec(
        name="test_alarm_loops",
        label="Проверка всех шлейфов охранной сигнализации",
        type="dropdown",
        group="Проверка работоспособности",
        required=True,
        options=DONE,
    ),
    FieldSpec(
        name="test_cctv_cameras",
        label="Проверка всех видеокамер",
        type="dropdown",
        group="Проверка работоспособности",
        required=True,
        options=DONE,
    ),
    FieldSpec(
        name="test_acs_points",
        label="Проверка всех точек доступа",
        type="dropdown",
        group="Проверка работоспособности",
        required=True,
        options=DONE,
    ),
    FieldSpec(
        name="test_perimeter_zones",
        label="Проверка всех зон периметра",
        type="dropdown",
        group="Проверка работоспособности",
        options=DONE,
    ),
    FieldSpec(
        name="test_transmission",
        label="Проверка доставки тревог на пульт",
        type="dropdown",
        group="Проверка работоспособности",
        required=True,
        options=DONE,
    ),
    FieldSpec(
        name="test_staff_actions",
        label="Действия персонала при тревоге отработаны",
        type="dropdown",
        group="Проверка работоспособности",
        options=VERDICT,
    ),
    FieldSpec(
        name="test_integration",
        label="Совместная работа подсистем ТСО",
        type="dropdown",
        group="Проверка работоспособности",
        options=VERDICT,
        description="Интеграция ОС, СОТ и СКУД по сценариям",
    ),
    FieldSpec(
        name="software_versions",
        label="Версии программного обеспечения и даты обновления",
        type="textarea",
        group="Проверка работоспособности",
        placeholder="ПО регистратора, версия, дата",
    ),
    FieldSpec(
        name="failures_period",
        label="Отказы и ложные срабатывания за период",
        type="textarea",
        group="Проверка работоспособности",
        placeholder="Дата, характер, принятые меры",
    ),
    FieldSpec(
        name="func_result",
        label="Результат проверки работоспособности",
        type="dropdown",
        group="Проверка работоспособности",
        required=True,
        options=("Работоспособно", "Работоспособно с замечаниями", "Не работоспособно"),
    ),
    # --- Заключение
    FieldSpec(
        name="defects_found",
        label="Выявленные дефекты и несоответствия",
        type="textarea",
        group="Заключение",
        required=True,
        placeholder="Перечень с указанием мест",
    ),
    FieldSpec(
        name="defects_critical",
        label="Дефекты, требующие немедленного устранения",
        type="textarea",
        group="Заключение",
        placeholder="Перечень критичных дефектов",
    ),
    FieldSpec(
        name="work_performed",
        label="Работы, выполненные при проверке",
        type="textarea",
        group="Заключение",
        placeholder="Чистка извещателей, замена аккумуляторов, юстировка камер",
    ),
    FieldSpec(
        name="condition_assessment",
        label="Оценка технического состояния ТСО",
        type="dropdown",
        group="Заключение",
        required=True,
        options=ASSESSMENT,
    ),
    FieldSpec(
        name="operation_permission",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=PERMISSION,
    ),
    FieldSpec(
        name="repair_required",
        label="Требуется ремонт или замена",
        type="dropdown",
        group="Заключение",
        options=YESNO,
    ),
    FieldSpec(
        name="repair_deadline",
        label="Срок устранения замечаний",
        type="date",
        group="Заключение",
    ),
    FieldSpec(
        name="next_check_date",
        label="Дата следующей проверки",
        type="date",
        group="Заключение",
        required=True,
    ),
    FieldSpec(
        name="recommendation",
        label="Рекомендации по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Мероприятия по устранению замечаний",
    ),
    FieldSpec(
        name="approver",
        label="Проверку согласовал (ФИО, должность)",
        type="text",
        group="Заключение",
        placeholder="Иванов И.И., начальник службы безопасности",
    ),
    FieldSpec(
        name="notes",
        label="Примечания",
        type="textarea",
        group="Заключение",
        placeholder="Дополнительная информация",
    ),
]


def main() -> None:
    build_template(OUTPUT, GROUPS, FIELDS)


if __name__ == "__main__":
    main()
