"""Генератор шаблона проверки автомобиля УАЗ Патриот.

Запуск (из корня проекта):

    python tools/build_uaz_template.py

Нормативная основа — ТР ТС 018/2011 «О безопасности колёсных транспортных
средств», приложение № 8 «Требования к транспортным средствам, находящимся в
эксплуатации»; ГОСТ 33997-2016; постановление Правительства РФ от 23.10.1993
№ 1090 (ПДД и Перечень неисправностей, при которых запрещается эксплуатация);
Федеральный закон от 10.12.1995 № 196-ФЗ, ст. 20; приказ Минтранса России
от 15.01.2021 № 9 (предрейсовый контроль технического состояния); приказ
Минтранса России от 12.05.2026 № 212 (правила обеспечения безопасности
перевозок); руководство по эксплуатации УАЗ Патриот (регламент ТО).

Важно: ГОСТ Р 51709-2001, который часто указывают в старых чек-листах,
отменён с 01.02.2018 приказом Росстандарта № 708-ст. Его место занял
ГОСТ 33997-2016.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "uaz_patriot_to.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
YESNO = ("Да", "Нет")
DECISION = ("Допущен", "Не допущен")

GROUPS = [
    "Общие сведения",
    "Документы и допуск к эксплуатации",
    "Проверка перед выездом",
    "Тормозная система",
    "Рулевое управление",
    "Шины и колёса",
    "Светотехника и обзорность",
    "Двигатель и его системы",
    "Трансмиссия и полный привод",
    "Подвеска, кузов и коррозия",
    "Электрооборудование и жидкости",
    "Заключение",
]

TRS = "ТР ТС 018/2011, приложение 8"
PERECHEN = "ПДД, Перечень неисправностей"

FIELDS: list[FieldSpec] = [
    # ---------------------------------------------------- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Подразделение и автоколонна",
        description="Организация, где эксплуатируется автомобиль",
    ),
    FieldSpec(
        name="vehicle_model",
        label="Модель автомобиля",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="УАЗ Патриот",
    ),
    FieldSpec(
        name="state_number",
        label="Государственный регистрационный знак",
        type="text",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="vin",
        label="Идентификационный номер (VIN)",
        type="text",
        group="Общие сведения",
        description=f"{TRS}, п. 12.1 — номер должен читаться и совпадать с документами",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
    ),
    FieldSpec(
        name="odometer",
        label="Пробег по одометру",
        type="number",
        group="Общие сведения",
        required=True,
        unit="км",
        placeholder="Значение одометра, км",
    ),
    FieldSpec(
        name="inspector",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Инженер по безопасности движения",
    ),
    FieldSpec(
        name="normative_base",
        label="Нормативная база проверки",
        type="textarea",
        group="Общие сведения",
        placeholder="ТР ТС 018/2011 прил. 8, ГОСТ 33997-2016, ПДД",
        description="Документы, по которым выполнялась проверка",
    ),
    # ------------------------------------------ Документы и допуск
    FieldSpec(
        name="sts_matches",
        label="СТС и ПТС соответствуют фактическим данным автомобиля",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 12.1",
    ),
    FieldSpec(
        name="registration_matches",
        label="Автомобиль зарегистрирован на предприятие, данные актуальны",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=VERDICT,
        description="Основные положения по допуску ТС к эксплуатации",
    ),
    FieldSpec(
        name="diagnostic_card",
        label="Диагностическая карта техосмотра действительна",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=VERDICT,
        description="Федеральный закон № 170-ФЗ, ст. 15 — применимость по виду использования",
    ),
    FieldSpec(
        name="osago",
        label="Полис ОСАГО действует на дату проверки",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="last_service_date",
        label="Дата последнего планового ТО",
        type="date",
        group="Документы и допуск к эксплуатации",
    ),
    FieldSpec(
        name="last_service_odometer",
        label="Пробег на дату последнего ТО",
        type="number",
        group="Документы и допуск к эксплуатации",
        unit="км",
    ),
    FieldSpec(
        name="service_interval_ok",
        label="Периодичность ТО не нарушена — не более 15 000 км или 12 месяцев",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        required=True,
        options=VERDICT,
        description="Регламент ТО УАЗ Патриот: межсервисный интервал 15 000 км или 12 месяцев",
    ),
    FieldSpec(
        name="service_book_filled",
        label="Сервисная книжка заполнена, записи о ТО непрерывны",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=VERDICT,
    ),
    FieldSpec(
        name="waybills_ok",
        label="Путевые листы оформлены и подписаны ответственным лицом",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=VERDICT,
        description="Приказ Минтранса России от 12.05.2026 № 212",
    ),
    FieldSpec(
        name="pre_trip_log",
        label="Журнал предрейсового контроля технического состояния ведётся",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        required=True,
        options=YESNO,
        description="Приказ Минтранса России от 15.01.2021 № 9",
    ),
    FieldSpec(
        name="medical_log",
        label="Журнал предрейсовых медосмотров ведётся, отметки есть",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=YESNO,
        description="Приказ Минздрава России от 30.05.2023 № 266н",
    ),
    FieldSpec(
        name="responsible_appointed",
        label="Ответственный за безопасность движения и выпуск ТС назначен приказом",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        options=YESNO,
        description="Федеральный закон № 196-ФЗ, ст. 20",
    ),
    FieldSpec(
        name="no_forbidden_faults",
        label="Запрещающие эксплуатацию неисправности при осмотре не выявлены",
        type="dropdown",
        group="Документы и допуск к эксплуатации",
        required=True,
        options=VERDICT,
        description=PERECHEN,
    ),
    # ------------------------------------------------ Проверка перед выездом
    FieldSpec(
        name="pre_trip_done",
        label="Осмотр проведён перед выездом с отметкой в журнале",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=YESNO,
        description="Приказ Минтранса России от 15.01.2021 № 9",
    ),
    FieldSpec(
        name="clean_glazing",
        label="Кузов, стёкла, зеркала и номерные знаки чистые, обзорность не ограничена",
        type="dropdown",
        group="Проверка перед выездом",
        options=VERDICT,
        description=f"{TRS}, раздел 4",
    ),
    FieldSpec(
        name="no_leaks",
        label="Подтёки масла и рабочих жидкостей под автомобилем отсутствуют",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 10.14 — каплепадение не допускается",
    ),
    FieldSpec(
        name="coolant_level",
        label="Уровень охлаждающей жидкости в расширительном бачке в норме",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="oil_level",
        label="Уровень моторного масла по щупу в пределах MIN–MAX",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="brake_fluid_level",
        label="Уровень тормозной жидкости в бачке в норме",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="ps_fluid_level",
        label="Уровень жидкости гидроусилителя руля в норме",
        type="dropdown",
        group="Проверка перед выездом",
        options=VERDICT,
        description=f"{TRS}, п. 2.6",
    ),
    FieldSpec(
        name="washer_level",
        label="Уровень жидкости стеклоомывателя достаточен",
        type="dropdown",
        group="Проверка перед выездом",
        options=VERDICT,
    ),
    FieldSpec(
        name="tires_visually_ok",
        label="Шины визуально целые, без порезов, вздутий и оголения корда",
        type="dropdown",
        group="Проверка перед выездом",
        options=STATE,
        description=f"{TRS}, п. 5.6",
    ),
    FieldSpec(
        name="tire_pressure_checked",
        label="Давление воздуха в шинах проверено манометром",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="lights_ok",
        label="Внешние световые приборы и световая сигнализация работают",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=STATE,
        description=f"{TRS}, раздел 3",
    ),
    FieldSpec(
        name="parking_brake_holds",
        label="Стояночный тормоз удерживает автомобиль",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 1.8 — уклон не менее 16 процентов",
    ),
    FieldSpec(
        name="release_time",
        label="Время выпуска на линию и ФИО выпускающего",
        type="text",
        group="Проверка перед выездом",
        placeholder="08:15, механик Петров П.П.",
    ),
    FieldSpec(
        name="pre_trip_remarks",
        label="Замечания, выявленные при предрейсовом осмотре",
        type="textarea",
        group="Проверка перед выездом",
        placeholder="Перечень замечаний или «нет»",
    ),
    FieldSpec(
        name="release_decision",
        label="Решение о выпуске на линию",
        type="dropdown",
        group="Проверка перед выездом",
        required=True,
        options=DECISION,
    ),
    # ---------------------------------------------------- Тормозная система
    FieldSpec(
        name="brake_pedal_travel",
        label="Ход педали тормоза не увеличен, педаль не проваливается",
        type="dropdown",
        group="Тормозная система",
        required=True,
        options=VERDICT,
        description=f"{TRS}, пп. 1.1–1.3",
    ),
    FieldSpec(
        name="brake_leak_free",
        label="Герметичность гидравлического тормозного привода не нарушена",
        type="dropdown",
        group="Тормозная система",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 1.11.2",
    ),
    FieldSpec(
        name="brake_lines_ok",
        label="Тормозные трубки и шланги без перегибов, трещин и коррозии",
        type="dropdown",
        group="Тормозная система",
        options=STATE,
        description=f"{TRS}, пп. 1.11.5, 1.13",
    ),
    FieldSpec(
        name="pads_front",
        label="Толщина тормозных колодок передней оси",
        type="number",
        group="Тормозная система",
        required=True,
        unit="мм",
        placeholder="Сравнить с минимальной по руководству",
    ),
    FieldSpec(
        name="pads_rear",
        label="Толщина тормозных колодок задней оси",
        type="number",
        group="Тормозная система",
        unit="мм",
    ),
    FieldSpec(
        name="discs_thickness",
        label="Остаточная толщина тормозных дисков",
        type="number",
        group="Тормозная система",
        unit="мм",
    ),
    FieldSpec(
        name="brake_fluid_clean",
        label="Тормозная жидкость без признаков загрязнения и обводнения",
        type="dropdown",
        group="Тормозная система",
        options=VERDICT,
    ),
    FieldSpec(
        name="brake_fluid_date",
        label="Дата замены тормозной жидкости",
        type="date",
        group="Тормозная система",
        description="Регламент ТО: не реже 30 000 км или 2 лет",
    ),
    FieldSpec(
        name="parking_brake_efficiency",
        label="Стояночная тормозная система удерживает ТС на уклоне не менее 16 процентов",
        type="dropdown",
        group="Тормозная система",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 1.8",
    ),
    FieldSpec(
        name="parking_brake_travel",
        label="Свободный ход рычага стояночного тормоза в пределах нормы",
        type="dropdown",
        group="Тормозная система",
        options=VERDICT,
    ),
    FieldSpec(
        name="vacuum_booster",
        label="Вакуумный усилитель тормозов работоспособен, утечек и шипения нет",
        type="dropdown",
        group="Тормозная система",
        options=STATE,
    ),
    FieldSpec(
        name="abs_lamp_off",
        label="Индикаторы тормозной системы и АБС после пуска не горят",
        type="dropdown",
        group="Тормозная система",
        required=True,
        options=VERDICT,
        description=f"{TRS}, пп. 1.12, 1.15",
    ),
    FieldSpec(
        name="no_pull_on_braking",
        label="Увод автомобиля в сторону при торможении отсутствует",
        type="dropdown",
        group="Тормозная система",
        options=VERDICT,
        description=f"{TRS}, п. 1.4 — разность тормозных сил на оси",
    ),
    FieldSpec(
        name="brake_specific_force",
        label="Удельная тормозная сила по результатам проверки",
        type="number",
        group="Тормозная система",
        placeholder="Не менее 0,50",
        description=f"{TRS}, таблицы 1.1–1.4",
    ),
    FieldSpec(
        name="brake_parts_ok",
        label="Трещины, остаточная деформация и повреждения тормозного привода отсутствуют",
        type="dropdown",
        group="Тормозная система",
        options=STATE,
        description=f"{TRS}, п. 1.11",
    ),
    # -------------------------------------------------- Рулевое управление
    FieldSpec(
        name="steering_free_play",
        label="Суммарный люфт рулевого колеса не превышает 10 градусов",
        type="dropdown",
        group="Рулевое управление",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 2.3 и {PERECHEN}, раздел 2",
    ),
    FieldSpec(
        name="steering_effort",
        label="Усилие на рулевом колесе изменяется плавно во всём диапазоне поворота",
        type="dropdown",
        group="Рулевое управление",
        options=VERDICT,
        description=f"{TRS}, п. 2.2",
    ),
    FieldSpec(
        name="power_steering_ok",
        label="Усилитель рулевого управления работоспособен",
        type="dropdown",
        group="Рулевое управление",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="no_self_steering",
        label="Самопроизвольный поворот рулевого колеса при работающем двигателе отсутствует",
        type="dropdown",
        group="Рулевое управление",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 2.5",
    ),
    FieldSpec(
        name="steering_joints_ok",
        label="Люфт в шарнирах рулевых тяг и соединениях рычагов отсутствует",
        type="dropdown",
        group="Рулевое управление",
        options=VERDICT,
        description=f"{TRS}, п. 2.4",
    ),
    FieldSpec(
        name="no_ps_leak",
        label="Подтекание рабочей жидкости в гидросистеме усилителя отсутствует",
        type="dropdown",
        group="Рулевое управление",
        options=VERDICT,
        description=f"{TRS}, п. 2.6",
    ),
    FieldSpec(
        name="steering_mount_ok",
        label="Рулевая колонка и картер рулевого механизма закреплены, крепёж в наличии",
        type="dropdown",
        group="Рулевое управление",
        options=STATE,
        description=f"{TRS}, п. 2.4",
    ),
    FieldSpec(
        name="tie_rods_ok",
        label="Рулевые тяги, наконечники и пыльники без разрывов и деформаций",
        type="dropdown",
        group="Рулевое управление",
        options=STATE,
    ),
    FieldSpec(
        name="ps_fluid_date",
        label="Дата замены жидкости гидроусилителя руля",
        type="date",
        group="Рулевое управление",
        description="Регламент ТО: не реже 45 000 км или 3 лет",
    ),
    FieldSpec(
        name="steering_play_norm",
        label="Свободный ход рулевого колеса до начала поворота колёс соответствует норме",
        type="dropdown",
        group="Рулевое управление",
        options=VERDICT,
    ),
    FieldSpec(
        name="steering_no_cracks",
        label="Трещины и остаточная деформация деталей рулевого привода отсутствуют",
        type="dropdown",
        group="Рулевое управление",
        options=STATE,
    ),
    # -------------------------------------------------------- Шины и колёса
    FieldSpec(
        name="tread_depth",
        label="Остаточная глубина рисунка протектора",
        type="number",
        group="Шины и колёса",
        required=True,
        unit="мм",
        placeholder="Не менее 1,6 для M1",
        description=f"{PERECHEN}, п. 5.4",
    ),
    FieldSpec(
        name="tread_wear_even",
        label="Износ шин равномерный, индикаторы износа не достигнуты",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
    ),
    FieldSpec(
        name="tires_no_damage",
        label="Шины без пробоев, порезов, расслоений, вздутий и оголения корда",
        type="dropdown",
        group="Шины и колёса",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 5.6",
    ),
    FieldSpec(
        name="tire_size_matches",
        label="Размерность, категория скорости и индекс несущей способности соответствуют руководству",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
        description=f"{TRS}, пп. 5.2.1–5.2.3",
    ),
    FieldSpec(
        name="tire_pressure_value",
        label="Давление воздуха в шинах по осям",
        type="text",
        group="Шины и колёса",
        placeholder="Передние 2,1 / задние 2,1 кгс/см²",
    ),
    FieldSpec(
        name="tire_dot_date",
        label="Дата выпуска шин по маркировке DOT",
        type="date",
        group="Шины и колёса",
    ),
    FieldSpec(
        name="tires_age_ok",
        label="Возраст шин не превышает предельный",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
    ),
    FieldSpec(
        name="same_axle_tires",
        label="На одну ось установлены шины одной размерности, конструкции и рисунка",
        type="dropdown",
        group="Шины и колёса",
        required=True,
        options=VERDICT,
        description=f"{PERECHEN}, п. 5.8",
    ),
    FieldSpec(
        name="winter_tires_ok",
        label="Зимние шины установлены на все колёса, остаточная глубина не менее 4 мм",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
        description=f"{PERECHEN}, п. 5.5",
    ),
    FieldSpec(
        name="studs_season_ok",
        label="Шипы противоскольжения применяются только в зимний период",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
        description=f"{PERECHEN}, п. 5.2 — запрет шипов в июне, июле и августе",
    ),
    FieldSpec(
        name="wheel_fasteners_ok",
        label="Крепёж колёс в наличии, болты и гайки затянуты с моментом по руководству",
        type="dropdown",
        group="Шины и колёса",
        required=True,
        options=STATE,
        description=f"{PERECHEN}, п. 5.7",
    ),
    FieldSpec(
        name="wheels_no_cracks",
        label="Диски без трещин, следов сварки и нарушения крепёжных отверстий",
        type="dropdown",
        group="Шины и колёса",
        options=STATE,
        description=f"{PERECHEN}, п. 5.7",
    ),
    FieldSpec(
        name="spare_wheel_ok",
        label="Запасное колесо укомплектовано, закреплено, давление проверено",
        type="dropdown",
        group="Шины и колёса",
        options=STATE,
        description=f"{TRS}, п. 10.12",
    ),
    FieldSpec(
        name="valves_present",
        label="На колёсах установлены золотники, а не заглушки и пробки",
        type="dropdown",
        group="Шины и колёса",
        options=VERDICT,
        description=f"{PERECHEN}, п. 5.11",
    ),
    # ------------------------------------------ Светотехника и обзорность
    FieldSpec(
        name="headlights_ok",
        label="Фары ближнего и дальнего света исправны, пучок под правостороннее движение",
        type="dropdown",
        group="Светотехника и обзорность",
        required=True,
        options=STATE,
        description=f"{TRS}, раздел 3",
    ),
    FieldSpec(
        name="windshield_light",
        label="Светопропускание ветрового стекла",
        type="number",
        group="Светотехника и обзорность",
        unit="%",
        placeholder="Не менее 70",
        description=f"{TRS}, п. 4.3",
    ),
    FieldSpec(
        name="windshield_no_cracks",
        label="Трещины на ветровом стекле в зоне очистки со стороны водителя отсутствуют",
        type="dropdown",
        group="Светотехника и обзорность",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 4.7",
    ),
    FieldSpec(
        name="wipers_ok",
        label="Стеклоочистители работоспособны и очищают зону",
        type="dropdown",
        group="Светотехника и обзорность",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 4.8",
    ),
    FieldSpec(
        name="washer_ok",
        label="Стеклоомыватель подаёт жидкость в зону очистки",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
        description=f"{TRS}, п. 4.9",
    ),
    FieldSpec(
        name="wiper_blades_ok",
        label="Щётки стеклоочистителя не изношены, полос неочищенного стекла нет",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
    ),
    FieldSpec(
        name="all_lights_ok",
        label="Габариты, стоп-сигналы, поворотники, задний ход и подсветка номера работают",
        type="dropdown",
        group="Светотехника и обзорность",
        required=True,
        options=STATE,
        description=PERECHEN,
    ),
    FieldSpec(
        name="lenses_ok",
        label="Рассеиватели световых приборов без трещин, разрушений и загрязнений",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
        description=f"{TRS}, п. 3.4",
    ),
    FieldSpec(
        name="mirrors_ok",
        label="Зеркала заднего вида в комплекте, закреплены и регулируются",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
        description=f"{TRS}, пп. 4.11–4.13",
    ),
    FieldSpec(
        name="sun_visors_ok",
        label="Противосолнечные козырьки в наличии и работоспособны",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
        description=f"{TRS}, п. 4.10",
    ),
    FieldSpec(
        name="defroster_ok",
        label="Обогрев и обдув ветрового стекла работоспособны",
        type="dropdown",
        group="Светотехника и обзорность",
        options=STATE,
        description=f"{TRS}, п. 10.2",
    ),
    FieldSpec(
        name="washer_volume",
        label="Объём залитой жидкости стеклоомывателя",
        type="number",
        group="Светотехника и обзорность",
        unit="л",
    ),
    FieldSpec(
        name="no_vision_block",
        label="Предметы, ограничивающие обзорность с места водителя, отсутствуют",
        type="dropdown",
        group="Светотехника и обзорность",
        options=VERDICT,
        description=f"{TRS}, п. 4.1",
    ),
    FieldSpec(
        name="extra_lights_legal",
        label="Дополнительные световые приборы установлены по требованиям регламента",
        type="dropdown",
        group="Светотехника и обзорность",
        options=VERDICT,
        description=f"{TRS}, п. 3.1",
    ),
    # -------------------------------------------------- Двигатель и системы
    FieldSpec(
        name="engine_oil_ok",
        label="Уровень моторного масла по щупу в пределах MIN–MAX",
        type="dropdown",
        group="Двигатель и его системы",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="oil_change_due",
        label="Масло и масляный фильтр заменены в пределах 15 000 км или 1 года",
        type="dropdown",
        group="Двигатель и его системы",
        required=True,
        options=VERDICT,
        description="Регламент ТО УАЗ Патриот",
    ),
    FieldSpec(
        name="oil_change_date",
        label="Дата замены моторного масла",
        type="date",
        group="Двигатель и его системы",
    ),
    FieldSpec(
        name="oil_condition_ok",
        label="Масло без признаков эмульсии и запаха топлива",
        type="dropdown",
        group="Двигатель и его системы",
        options=VERDICT,
    ),
    FieldSpec(
        name="engine_no_leaks",
        label="Подтёки масла из двигателя — прокладки, сальники, поддон — отсутствуют",
        type="dropdown",
        group="Двигатель и его системы",
        options=STATE,
        description=f"{TRS}, п. 10.14",
    ),
    FieldSpec(
        name="coolant_condition_ok",
        label="Антифриз без примесей и загрязнений, уровень в норме",
        type="dropdown",
        group="Двигатель и его системы",
        options=VERDICT,
    ),
    FieldSpec(
        name="coolant_change_date",
        label="Дата замены антифриза",
        type="date",
        group="Двигатель и его системы",
        description="Регламент ТО: не реже 60 000 км или 4 лет",
    ),
    FieldSpec(
        name="cooling_sealed",
        label="Система охлаждения герметична, следов подтекания нет",
        type="dropdown",
        group="Двигатель и его системы",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 10.14",
    ),
    FieldSpec(
        name="drive_belt_ok",
        label="Ремень привода навесных агрегатов целый, натяжение в норме",
        type="dropdown",
        group="Двигатель и его системы",
        options=STATE,
    ),
    FieldSpec(
        name="timing_drive_ok",
        label="Привод ГРМ без повреждений, натяжение и замена по регламенту",
        type="dropdown",
        group="Двигатель и его системы",
        options=STATE,
    ),
    FieldSpec(
        name="hoses_ok",
        label="Патрубки и хомуты системы охлаждения без трещин и подтеканий",
        type="dropdown",
        group="Двигатель и его системы",
        options=STATE,
    ),
    FieldSpec(
        name="fuel_system_sealed",
        label="Система питания герметична, подтеканий топлива нет",
        type="dropdown",
        group="Двигатель и его системы",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 9.6",
    ),
    FieldSpec(
        name="no_strange_noise",
        label="Посторонние шумы, стуки и вибрации при работе двигателя отсутствуют",
        type="dropdown",
        group="Двигатель и его системы",
        options=VERDICT,
        description=f"{TRS}, п. 9.9",
    ),
    FieldSpec(
        name="check_engine_off",
        label="Индикатор неисправности двигателя после пуска не горит",
        type="dropdown",
        group="Двигатель и его системы",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 9.5",
    ),
    FieldSpec(
        name="co_value",
        label="Содержание оксида углерода на минимальной частоте холостого хода",
        type="number",
        group="Двигатель и его системы",
        unit="%",
        description=f"{TRS}, таблица 9.1",
    ),
    # ------------------------------------------ Трансмиссия и полный привод
    FieldSpec(
        name="clutch_ok",
        label="Сцепление включается плавно, пробуксовки и рывков нет",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
    ),
    FieldSpec(
        name="clutch_pedal_free_play",
        label="Свободный ход педали сцепления соответствует норме",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=VERDICT,
    ),
    FieldSpec(
        name="gearbox_ok",
        label="Коробка передач переключается без хруста и затруднений",
        type="dropdown",
        group="Трансмиссия и полный привод",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="gearbox_no_leaks",
        label="Подтекание масла из коробки передач и раздаточной коробки отсутствует",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
        description=f"{TRS}, п. 10.14",
    ),
    FieldSpec(
        name="gearbox_oil_level",
        label="Уровень масла в коробке передач и раздаточной коробке в норме",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=VERDICT,
    ),
    FieldSpec(
        name="axle_oil_level",
        label="Уровень масла в ведущих мостах в норме",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=VERDICT,
    ),
    FieldSpec(
        name="transmission_oil_date",
        label="Дата замены масла в коробке передач и редукторах",
        type="date",
        group="Трансмиссия и полный привод",
        description="Регламент ТО: не реже 45 000 км или 3 лет",
    ),
    FieldSpec(
        name="transfer_case_ok",
        label="Раздаточная коробка переключается, фиксация передач есть",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
    ),
    FieldSpec(
        name="driveshaft_ok",
        label="Шарниры карданных валов без люфта, крестовины и подвесной подшипник целы",
        type="dropdown",
        group="Трансмиссия и полный привод",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 10.6",
    ),
    FieldSpec(
        name="driveshaft_mount_ok",
        label="Крепление карданной передачи затянуто, ослаблений и разрушений нет",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
        description=f"{TRS}, п. 10.6",
    ),
    FieldSpec(
        name="four_wheel_drive_ok",
        label="Полный привод подключается и отключается",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
    ),
    FieldSpec(
        name="transmission_backlash_ok",
        label="Люфты в шлицевых соединениях и редукторах мостов в пределах нормы",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=VERDICT,
    ),
    FieldSpec(
        name="axle_seals_ok",
        label="Подтекания масла из мостов и сальников полуосей отсутствуют",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
    ),
    FieldSpec(
        name="cv_boots_ok",
        label="Пыльники шарниров и поворотных кулаков целые, стуков нет",
        type="dropdown",
        group="Трансмиссия и полный привод",
        options=STATE,
    ),
    # -------------------------------------- Подвеска, кузов и коррозия
    FieldSpec(
        name="no_accident_traces",
        label="Следы ДТП и ремонтных воздействий на силовых элементах кузова и рамы отсутствуют",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="geometry_ok",
        label="Геометрия кузова не нарушена, зазоры дверей и капота равномерны",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=VERDICT,
    ),
    FieldSpec(
        name="no_through_corrosion",
        label="Сквозная коррозия несущих элементов кузова и рамы отсутствует",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        required=True,
        options=VERDICT,
        description=f"{TRS}, п. 10.15",
    ),
    FieldSpec(
        name="corrosion_map",
        label="Площадь и локализация коррозионных повреждений",
        type="textarea",
        group="Подвеска, кузов и коррозия",
        placeholder="Пороги, арки, днище или «не обнаружено»",
    ),
    FieldSpec(
        name="shock_absorbers_ok",
        label="Амортизаторы работоспособны, подтеканий нет",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 10.15",
    ),
    FieldSpec(
        name="suspension_mount_ok",
        label="Крепление амортизаторов и деталей подвески затянуто, разрушений нет",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
        description=f"{TRS}, п. 10.6",
    ),
    FieldSpec(
        name="springs_ok",
        label="Пружины и рессоры целые, без трещин и проседания",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
    ),
    FieldSpec(
        name="ball_joints_ok",
        label="Шаровые опоры и сайлентблоки без люфта и разрывов",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
    ),
    FieldSpec(
        name="brackets_no_cracks",
        label="Трещины и разрушения щёк кронштейнов подвески отсутствуют",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
        description=f"{TRS}, п. 10.16",
    ),
    FieldSpec(
        name="body_mount_ok",
        label="Крепление кузова к раме в норме, ослаблений нет",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
    ),
    FieldSpec(
        name="mudguards_ok",
        label="Подкрылки и брызговики в комплекте",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
        description=f"{TRS}, п. 10.17",
    ),
    FieldSpec(
        name="doors_locks_ok",
        label="Двери, замки, стёкла и петли работают, люфтов нет",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
        description=f"{TRS}, п. 10.2",
    ),
    FieldSpec(
        name="body_repair_date",
        label="Дата последнего кузовного ремонта",
        type="date",
        group="Подвеска, кузов и коррозия",
    ),
    FieldSpec(
        name="odometer_check",
        label="Пробег сверен с учётными данными подразделения",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=VERDICT,
    ),
    FieldSpec(
        name="tow_hitch_ok",
        label="Тягово-сцепное устройство исправно, диаметр шара не менее 49,6 мм",
        type="dropdown",
        group="Подвеска, кузов и коррозия",
        options=STATE,
        description=f"{TRS}, п. 6.8.5",
    ),
    # ------------------------------- Электрооборудование и жидкости
    FieldSpec(
        name="battery_mount_ok",
        label="Аккумуляторная батарея закреплена, клеммы чистые и затянуты",
        type="dropdown",
        group="Электрооборудование и жидкости",
        required=True,
        options=STATE,
        description=f"{TRS}, п. 10.10",
    ),
    FieldSpec(
        name="battery_voltage",
        label="Напряжение на клеммах АКБ при неработающем двигателе",
        type="number",
        group="Электрооборудование и жидкости",
        unit="В",
        placeholder="Не менее 12,4",
    ),
    FieldSpec(
        name="charging_voltage",
        label="Напряжение бортовой сети при работающем двигателе",
        type="number",
        group="Электрооборудование и жидкости",
        unit="В",
        placeholder="13,5–14,8",
    ),
    FieldSpec(
        name="battery_date",
        label="Дата изготовления аккумуляторной батареи",
        type="date",
        group="Электрооборудование и жидкости",
    ),
    FieldSpec(
        name="generator_ok",
        label="Генератор обеспечивает зарядку, ремень натянут",
        type="dropdown",
        group="Электрооборудование и жидкости",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="starter_ok",
        label="Стартер проворачивает двигатель уверенно",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
    ),
    FieldSpec(
        name="wiring_ok",
        label="Провода и жгуты без разрушения изоляции и следов пробоя",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
        description=f"{TRS}, п. 10.9",
    ),
    FieldSpec(
        name="dashboard_ok",
        label="Контрольные лампы и приборы щитка работоспособны",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
        description=f"{TRS}, п. 10.1",
    ),
    FieldSpec(
        name="speedometer_ok",
        label="Спидометр работоспособен, демонтаж отсутствует",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
        description=f"{TRS}, п. 10.5",
    ),
    FieldSpec(
        name="horn_ok",
        label="Звуковой сигнал исправен, звук непрерывный и монотонный",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
        description=f"{TRS}, п. 10.4",
    ),
    FieldSpec(
        name="toolkit_ok",
        label="Домкрат, баллонный ключ и знак аварийной остановки в комплекте",
        type="dropdown",
        group="Электрооборудование и жидкости",
        required=True,
        options=YESNO,
        description=f"{TRS}, п. 11.1",
    ),
    FieldSpec(
        name="first_aid_ok",
        label="Аптечка первой помощи в наличии и укомплектована",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=YESNO,
        description=f"{TRS}, п. 11.3",
    ),
    FieldSpec(
        name="extinguisher_ok",
        label="Огнетушитель не менее 1 л в наличии, пломбы целы, срок не истёк",
        type="dropdown",
        group="Электрооборудование и жидкости",
        required=True,
        options=VERDICT,
        description=f"{TRS}, пп. 11.4–11.5",
    ),
    FieldSpec(
        name="fluids_all_ok",
        label="Уровни масла, охлаждающей, тормозной жидкости, жидкости ГУР и омывателя в норме",
        type="dropdown",
        group="Электрооборудование и жидкости",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="era_glonass_ok",
        label="Устройство вызова экстренных служб работоспособно",
        type="dropdown",
        group="Электрооборудование и жидкости",
        options=STATE,
        description=f"{TRS}, п. 10.20",
    ),
    # ------------------------------------------------------------ Заключение
    FieldSpec(
        name="technical_state",
        label="Оценка технического состояния автомобиля",
        type="dropdown",
        group="Заключение",
        required=True,
        options=(
            "Исправен",
            "Работоспособен",
            "Ограниченно работоспособен",
            "Неисправен",
        ),
    ),
    FieldSpec(
        name="defects_found",
        label="Выявленные неисправности и замечания",
        type="textarea",
        group="Заключение",
        placeholder="Перечень или «не выявлено»",
    ),
    FieldSpec(
        name="next_service_odometer",
        label="Пробег для следующего ТО",
        type="number",
        group="Заключение",
        unit="км",
    ),
    FieldSpec(
        name="next_service_date",
        label="Дата следующего ТО",
        type="date",
        group="Заключение",
    ),
    FieldSpec(
        name="operation_allowed",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=(
            "Допускается",
            "Допускается с ограничениями",
            "Не допускается",
        ),
    ),
    FieldSpec(
        name="conclusion",
        label="Вывод по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Краткий вывод",
    ),
]


if __name__ == "__main__":
    build_template(OUTPUT, GROUPS, FIELDS)
