"""Генератор шаблона проверки стационарного подъёмного сооружения.

Запуск (из корня проекта):

    python tools/build_lifting_template.py

Нормативная основа — Федеральные нормы и правила в области промышленной
безопасности «Правила безопасности опасных производственных объектов, на
которых используются подъёмные сооружения», утв. приказом Ростехнадзора
от 26.11.2020 № 461 (ред. от 16.04.2026); Федеральный закон от 21.07.1997
№ 116-ФЗ; постановления Правительства РФ № 1371, № 2168, № 1365; приказ
Ростехнадзора № 285; ТР ТС 010/2011; ГОСТ 33166.1-2014; ГОСТ 34018.1-2024;
ГОСТ 35321-2025; приказы Минтруда № 753н, № 903н, № 767н, № 782н;
ГОСТ 12.4.026-2015.

Важное ограничение: по п. 3 ФНП № 461 из области применения исключены, в
частности, краны мостового типа и консольные краны грузоподъёмностью до 10 т
включительно с управлением с пола, электрические тали до 10 т как
самостоятельные ПС и подъёмники с высотой подъёма до 6 м. Для них проверка
ведётся по ТР ТС 010/2011, руководству по эксплуатации и приказам Минтруда,
а пункты со ссылкой на ФНП отмечаются как «Не применимо». Первый пункт
шаблона предназначен именно для фиксации этого выбора.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "podyomnoe_sooruzhenie.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
YESNO = ("Да", "Нет")
ASSESSMENT = (
    "Исправно",
    "Работоспособно",
    "Ограниченно работоспособно",
    "Не работоспособно",
)
PERMISSION = ("Допускается", "Допускается с ограничениями", "Не допускается")

FNP = "ФНП № 461"

GROUPS = [
    "Общие сведения",
    "Организация эксплуатации и документация",
    "Паспорт и маркировка",
    "Металлоконструкции, тормоза и механизмы",
    "Канаты, цепи и крюки",
    "Грузозахватные приспособления и тара",
    "Приборы безопасности",
    "Управление, сигнализация и связь",
    "Крановый путь и противоугонные устройства",
    "Электробезопасность и заземление",
    "Осмотры, освидетельствование и персонал",
    "Заключение",
]

FIELDS: list[FieldSpec] = [
    # ---------------------------------------------------- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Цех, участок, подразделение",
    ),
    FieldSpec(
        name="ps_type",
        label="Тип подъёмного сооружения",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Мостовой кран, кран-балка, консольный кран",
        description="От типа зависит применимость ФНП № 461, п. 3",
    ),
    FieldSpec(
        name="ps_model",
        label="Модель и заводской номер",
        type="text",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="fnp_applies",
        label="ПС относится к области применения ФНП № 461",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=VERDICT,
        description=(
            f"{FNP}, п. 3 — исключены краны до 10 т с управлением с пола, "
            "тали до 10 т, подъёмники до 6 м"
        ),
    ),
    FieldSpec(
        name="exclusion_clause",
        label="Подпункт пункта 3, по которому ПС исключено из области применения",
        type="text",
        group="Общие сведения",
        placeholder="Указать подпункт или «не исключено»",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
    ),
    FieldSpec(
        name="inspector",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Инженер по надзору за подъёмными сооружениями",
    ),
    FieldSpec(
        name="capacity",
        label="Грузоподъёмность по паспорту",
        type="number",
        group="Общие сведения",
        required=True,
        unit="т",
    ),
    FieldSpec(
        name="normative_base",
        label="Нормативная база проверки",
        type="textarea",
        group="Общие сведения",
        placeholder="ФНП № 461, ТР ТС 010/2011, руководство по эксплуатации",
    ),
    # ------------------------------------ Организация эксплуатации и документы
    FieldSpec(
        name="opo_registered",
        label="ОПО, на котором эксплуатируется ПС, зарегистрирован в реестре ОПО",
        type="dropdown",
        group="Организация эксплуатации и документация",
        required=True,
        options=VERDICT,
        description=(f"{FNP}, п. 142 и постановление Правительства РФ от 24.11.1998 № 1371"),
    ),
    FieldSpec(
        name="opo_reg_number",
        label="Регистрационный номер и дата регистрации ОПО",
        type="text",
        group="Организация эксплуатации и документация",
    ),
    FieldSpec(
        name="hazard_class",
        label="Класс опасности ОПО определён с учётом характеристик ПС",
        type="dropdown",
        group="Организация эксплуатации и документация",
        required=True,
        options=VERDICT,
        description="Федеральный закон от 21.07.1997 № 116-ФЗ, ст. 2",
    ),
    FieldSpec(
        name="responsible_appointed",
        label="Назначены три ответственных ИТР: за производственный контроль, за содержание ПС и за безопасное производство работ",
        type="dropdown",
        group="Организация эксплуатации и документация",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 22, подпункт «и»",
    ),
    FieldSpec(
        name="responsible_orders_ok",
        label="Приказы о назначении ответственных ИТР актуальны",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
    ),
    FieldSpec(
        name="responsible_certified",
        label="Ответственные ИТР аттестованы по области «Требования промышленной безопасности к подъёмным сооружениям»",
        type="dropdown",
        group="Организация эксплуатации и документация",
        required=True,
        options=VERDICT,
        description=(
            "Постановление Правительства РФ от 25.10.2019 № 1365 и "
            "приказ Ростехнадзора от 09.08.2023 № 285"
        ),
    ),
    FieldSpec(
        name="production_control_ok",
        label="Производственный контроль организован, план мероприятий имеется",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
        description=(f"{FNP}, п. 146 и постановление Правительства РФ от 18.12.2020 № 2168"),
    ),
    FieldSpec(
        name="maintenance_schedule_ok",
        label="Утверждён порядок осмотров, технических обслуживаний и ремонтов, графики ППР имеются",
        type="dropdown",
        group="Организация эксплуатации и документация",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 147",
    ),
    FieldSpec(
        name="ppr_available",
        label="ППР и технологические карты для работ, требующих их разработки, имеются",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
        description=f"{FNP}, п. 98",
    ),
    FieldSpec(
        name="shift_log_kept",
        label="Вахтенный (сменный) журнал ведётся",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=YESNO,
        description=f"{FNP}, п. 147",
    ),
    FieldSpec(
        name="repair_log_kept",
        label="Журнал технического обслуживания и ремонтов ПС ведётся",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=YESNO,
        description=f"{FNP}, п. 147",
    ),
    FieldSpec(
        name="sgp_log_kept",
        label="Журнал учёта и периодического осмотра грузозахватных приспособлений и тары ведётся",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
        description=f"{FNP}, пп. 137, 225",
    ),
    FieldSpec(
        name="instructions_issued",
        label="Производственные инструкции выданы под подпись крановщику, стропальщику, слесарю и наладчику приборов",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
        description=f"{FNP}, п. 152",
    ),
    FieldSpec(
        name="commissioning_docs",
        label="Документы о пуске ПС в работу имеются: акт готовности, запись в паспорте, решение руководителя",
        type="dropdown",
        group="Организация эксплуатации и документация",
        options=VERDICT,
        description=f"{FNP}, пп. 135–142",
    ),
    FieldSpec(
        name="last_order_date",
        label="Дата и номер последнего приказа о назначении ответственных ИТР",
        type="text",
        group="Организация эксплуатации и документация",
    ),
    # -------------------------------------------------- Паспорт и маркировка
    FieldSpec(
        name="passport_available",
        label="Паспорт ПС в наличии и содержит отметки о монтаже и наладке",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 141, подпункт «б»",
    ),
    FieldSpec(
        name="manual_available",
        label="Руководство по эксплуатации ПС в наличии",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 141",
    ),
    FieldSpec(
        name="conformity_document",
        label="Сертификат соответствия ТР ТС 010/2011 или заключение экспертизы промышленной безопасности имеется",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
        description=(
            f"{FNP}, п. 141 и ТР ТС 010/2011, решение Комиссии Таможенного союза "
            "от 18.10.2011 № 823"
        ),
    ),
    FieldSpec(
        name="passport_data_matches",
        label="Паспортные данные — тип, заводской номер, год изготовления, грузоподъёмность, пролёт — соответствуют фактическим",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="plate_available",
        label="Табличка с заводским номером, грузоподъёмностью и датами освидетельствования установлена",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 121",
    ),
    FieldSpec(
        name="plate_dates_valid",
        label="Даты следующего освидетельствования на табличке не истекли",
        type="dropdown",
        group="Паспорт и маркировка",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 121",
    ),
    FieldSpec(
        name="service_life_ok",
        label="Фактический срок службы не превышает указанный изготовителем либо продлён экспертизой",
        type="dropdown",
        group="Паспорт и маркировка",
        options=VERDICT,
        description=f"{FNP}, п. 9, подпункт «д»",
    ),
    FieldSpec(
        name="gzp_capacity_reduced",
        label="При оснащении грейфером или электромагнитом полезная грузоподъёмность снижена по паспорту",
        type="dropdown",
        group="Паспорт и маркировка",
        options=VERDICT,
        description=f"{FNP}, приложение № 1, таблица 1",
    ),
    FieldSpec(
        name="classification_group",
        label="Группа классификации (режима работы) по паспорту",
        type="text",
        group="Паспорт и маркировка",
        placeholder="Например, А4 или А5",
        description="ГОСТ 33709.1-2015",
    ),
    FieldSpec(
        name="manufacture_year",
        label="Год изготовления и нормативный срок службы",
        type="text",
        group="Паспорт и маркировка",
        placeholder="2014, 20 лет",
    ),
    # ---------------------------- Металлоконструкции, тормоза и механизмы
    FieldSpec(
        name="metal_no_cracks",
        label="В металлоконструкциях отсутствуют трещины и недопустимые остаточные деформации",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «а»",
    ),
    FieldSpec(
        name="joints_ok",
        label="Сварные, клёпаные и болтовые соединения не имеют ослабления и видимых дефектов",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «б»",
    ),
    FieldSpec(
        name="cabin_ladders_ok",
        label="Состояние кабины, лестниц, площадок и ограждений соответствует требованиям",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «в»",
    ),
    FieldSpec(
        name="axles_pins_ok",
        label="Крепление осей и пальцев надёжно, смещений и недопустимого износа нет",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=STATE,
        description=f"{FNP}, п. 170, подпункт «д»",
    ),
    FieldSpec(
        name="hoist_brake_adjusted",
        label="Тормоз механизма подъёма отрегулирован на тормозной момент по паспорту",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 171",
    ),
    FieldSpec(
        name="travel_brakes_adjusted",
        label="Тормоза механизмов передвижения крана и грузовой тележки отрегулированы",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=STATE,
        description=f"{FNP}, п. 171",
    ),
    FieldSpec(
        name="brake_stroke_ok",
        label="Ход тормоза и отход колодок соответствуют руководству по эксплуатации",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
    ),
    FieldSpec(
        name="brake_linings_ok",
        label="Износ тормозных накладок не превышает половины первоначальной толщины, заклёпки не выступают",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        required=True,
        options=VERDICT,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="brake_pulleys_ok",
        label="Тормозные шкивы без трещин и обломов, износ обода не более 25 процентов",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="travel_wheels_ok",
        label="Ходовые колёса без трещин, износ реборды не более 50 процентов, уменьшение диаметра не более 2 процентов",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="block_groove_ok",
        label="Износ ручья блока не превышает 40 процентов первоначального радиуса",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="drum_ok",
        label="Барабаны без трещин, износ ручья по профилю не более 2 мм",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="counterweight_ok",
        label="Масса противовеса и балласта соответствует чертежу и паспорту",
        type="dropdown",
        group="Металлоконструкции, тормоза и механизмы",
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «е»",
    ),
    FieldSpec(
        name="brake_torque_value",
        label="Фактический тормозной момент механизма подъёма",
        type="number",
        group="Металлоконструкции, тормоза и механизмы",
        unit="Н·м",
    ),
    # ------------------------------------------- Канаты, цепи и крюки
    FieldSpec(
        name="ropes_match_passport",
        label="Канаты соответствуют паспорту по назначению, длине, диаметру и коэффициенту использования",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 191–194, приложение № 1",
    ),
    FieldSpec(
        name="rope_certificates",
        label="Сертификаты предприятия-изготовителя на стальные канаты имеются",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=VERDICT,
        description=f"{FNP}, п. 191",
    ),
    FieldSpec(
        name="rope_fastening_ok",
        label="Крепление каната соответствует ранее принятой конструкции, предусмотренной документацией",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 193",
    ),
    FieldSpec(
        name="rope_breaks_ok",
        label="Число видимых обрывов проволок каната не превышает браковочных норм",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 270, 272, таблица 3",
    ),
    FieldSpec(
        name="rope_no_defects",
        label="На канате отсутствуют разрыв пряди, корзинообразность, заломы, следы электрической дуги и перегрева",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 270",
    ),
    FieldSpec(
        name="rope_wear_ok",
        label="Поверхностный и внутренний износ, коррозия и уменьшение диаметра каната не превышают браковочных значений",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=VERDICT,
        description=f"{FNP}, п. 270",
    ),
    FieldSpec(
        name="chains_certified",
        label="Стальные цепи сертифицированы и соответствуют марке и разрывному усилию по паспорту",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=VERDICT,
        description=f"{FNP}, пп. 195–197",
    ),
    FieldSpec(
        name="chains_elongation_ok",
        label="Удлинение звена цепи не более 3 процентов, уменьшение диаметра сечения в допустимых пределах",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=VERDICT,
        description=f"{FNP}, п. 272",
    ),
    FieldSpec(
        name="hook_no_defects",
        label="Крюк не имеет трещин, надрывов и остаточных деформаций",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=STATE,
        description=f"{FNP}, таблица 4",
    ),
    FieldSpec(
        name="hook_wear_ok",
        label="Износ зева крюка не превышает 10 процентов первоначальной высоты вертикального сечения",
        type="dropdown",
        group="Канаты, цепи и крюки",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 275, таблица 4",
    ),
    FieldSpec(
        name="hook_latch_ok",
        label="Крюк снабжён предохранительным замком, замок исправен",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=STATE,
    ),
    FieldSpec(
        name="hook_ndt_done",
        label="Ревизия кованых крюков методом неразрушающего контроля проведена",
        type="dropdown",
        group="Канаты, цепи и крюки",
        options=VERDICT,
        description=(
            f"{FNP}, п. 170 — обязательно для кранов, транспортирующих "
            "расплавленный металл и жидкий шлак"
        ),
    ),
    FieldSpec(
        name="hook_stop_distance",
        label="Расстояние между крюковой подвеской и упором при срабатывании концевого выключателя",
        type="number",
        group="Канаты, цепи и крюки",
        unit="мм",
        description=f"{FNP}, п. 170",
    ),
    FieldSpec(
        name="hook_throat_height",
        label="Высота вертикального сечения зева крюка",
        type="number",
        group="Канаты, цепи и крюки",
        unit="мм",
    ),
    FieldSpec(
        name="last_hook_revision",
        label="Дата последней ревизии крюка и осмотра канатов",
        type="date",
        group="Канаты, цепи и крюки",
    ),
    # -------------------------------- Грузозахватные приспособления и тара
    FieldSpec(
        name="sgp_marked",
        label="Съёмные грузозахватные приспособления и тара имеют маркировку с грузоподъёмностью и учётным номером",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 218 — отсутствие маркировки является признаком негодности",
    ),
    FieldSpec(
        name="sgp_capacity_ok",
        label="Грузоподъёмность приспособлений соответствует массе и характеру перемещаемых грузов",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
    ),
    FieldSpec(
        name="sgp_tested",
        label="Акты испытаний приспособлений и тары имеются",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 222, 229–234",
    ),
    FieldSpec(
        name="rope_slings_ok",
        label="Канатные стропы не имеют обрывов проволок сверх браковочной таблицы",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
        description=f"{FNP}, п. 271, таблица 3",
    ),
    FieldSpec(
        name="textile_slings_ok",
        label="Текстильные стропы без поперечных порезов, расслоений и загрязнений более половины длины",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
        description=f"{FNP}, п. 273",
    ),
    FieldSpec(
        name="sgp_metal_ok",
        label="Металлические элементы приспособлений без трещин, износа 10 процентов и деформаций более 3 процентов",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
        description=f"{FNP}, п. 274",
    ),
    FieldSpec(
        name="sgp_checks_logged",
        label="Результаты осмотров приспособлений и тары заносятся в журнал",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
        description=f"{FNP}, п. 225",
    ),
    FieldSpec(
        name="sgp_inspection_periods",
        label="Стропы осматриваются не реже 1 раза в 10 дней, траверсы, клещи, захваты и тара — не реже 1 раза в месяц",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 224",
    ),
    FieldSpec(
        name="sgp_annual_revision",
        label="Траверсы, клещи и захваты ежегодно подвергаются частичной разборке и ревизии",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        options=VERDICT,
        description=f"{FNP}, п. 220",
    ),
    FieldSpec(
        name="sgp_defective_removed",
        label="Негодные и немаркированные приспособления удалены из мест производства работ",
        type="dropdown",
        group="Грузозахватные приспособления и тара",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 218",
    ),
    FieldSpec(
        name="sgp_last_dates",
        label="Дата последнего осмотра стропов и дата последнего испытания приспособлений",
        type="text",
        group="Грузозахватные приспособления и тара",
    ),
    # -------------------------------------------------- Приборы безопасности
    FieldSpec(
        name="load_limiter_ok",
        label="Ограничитель грузоподъёмности, предусмотренный паспортом, установлен и работоспособен",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 259–262",
    ),
    FieldSpec(
        name="load_limiter_threshold",
        label="Ограничитель грузоподъёмности отключает механизмы при перегрузке не более 25 процентов",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 262 — для кранов мостового типа без отрыва груза",
    ),
    FieldSpec(
        name="limiter_blocks_lifting",
        label="После срабатывания ограничителя включение механизмов, кроме опускания груза, невозможно",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 262",
    ),
    FieldSpec(
        name="upper_limit_switch",
        label="Ограничитель предельного верхнего положения грузозахватного органа останавливает механизм подъёма",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 259",
    ),
    FieldSpec(
        name="lower_limit_switch",
        label="Ограничитель нижнего предельного положения работоспособен",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 259",
    ),
    FieldSpec(
        name="travel_limit_switches",
        label="Концевые выключатели ограничения хода крана и тележки ограничивают движение в обоих направлениях",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 259",
    ),
    FieldSpec(
        name="power_line_limiter",
        label="Ограничитель опасного приближения к линии электропередачи работоспособен",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 266, приложение № 9",
    ),
    FieldSpec(
        name="recorder_ok",
        label="Регистратор параметров работы работоспособен, часы и календарь корректны",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 268",
    ),
    FieldSpec(
        name="recorder_read_period",
        label="Данные регистратора считываются и расшифровываются не реже 1 раза в 6 месяцев",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 24",
    ),
    FieldSpec(
        name="safety_devices_sealed",
        label="Приборы безопасности опломбированы после монтажа, наладки, ремонта или реконструкции",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, пп. 48–55",
    ),
    FieldSpec(
        name="checks_documented",
        label="Проверка работоспособности ограничителей и указателей оформлена актом",
        type="dropdown",
        group="Приборы безопасности",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 269",
    ),
    FieldSpec(
        name="limiter_check_method",
        label="Проверка ограничителя выполнена грузами или аттестованным устройством нагружения с погрешностью не более 3 процентов",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 261",
    ),
    FieldSpec(
        name="wind_speed_indicator",
        label="Указатель предельной скорости ветра и указатель угла наклона работоспособны",
        type="dropdown",
        group="Приборы безопасности",
        options=VERDICT,
        description=f"{FNP}, п. 267",
    ),
    FieldSpec(
        name="last_limiter_check",
        label="Дата последней проверки ограничителя и последнего считывания регистратора",
        type="text",
        group="Приборы безопасности",
    ),
    # -------------------------------- Управление, сигнализация и связь
    FieldSpec(
        name="signal_order_ok",
        label="Порядок обмена сигналами между стропальщиком и крановщиком установлен",
        type="dropdown",
        group="Управление, сигнализация и связь",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 248, приложение № 7",
    ),
    FieldSpec(
        name="signal_briefing_done",
        label="При смене участка работы крановщики и стропальщики проинструктированы под подпись",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 249",
    ),
    FieldSpec(
        name="signaller_appointed",
        label="При непросматриваемой зоне и отсутствии связи назначен сигнальщик из числа стропальщиков",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 153",
    ),
    FieldSpec(
        name="communication_ok",
        label="Радио- или телефонная связь между крановщиком и стропальщиком работоспособна",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=STATE,
        description=f"{FNP}, п. 153",
    ),
    FieldSpec(
        name="emergency_stop_ok",
        label="Кнопка аварийной остановки на пульте управления работоспособна",
        type="dropdown",
        group="Управление, сигнализация и связь",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="lighting_ok",
        label="Рабочее и ремонтное освещение зоны работы, кабины и подходов соответствует нормам",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «и»",
    ),
    FieldSpec(
        name="indicators_ok",
        label="Световые и звуковые указатели и сигнализаторы работоспособны",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=STATE,
    ),
    FieldSpec(
        name="control_panel_ok",
        label="Пульт управления без повреждений корпуса, кнопок и кабеля, маркировка читаема",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
    ),
    FieldSpec(
        name="floor_control_passage",
        label="Для управления с пола или по радио обеспечен свободный проход вдоль всего пути следования",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 117",
    ),
    FieldSpec(
        name="bridge_platform_permit",
        label="Работы с площадок мостового крана выполняются по наряду-допуску",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 120",
    ),
    FieldSpec(
        name="power_line_permit",
        label="Работа ближе 30 м от крайнего провода воздушной линии более 50 В ведётся по наряду-допуску",
        type="dropdown",
        group="Управление, сигнализация и связь",
        options=VERDICT,
        description=f"{FNP}, п. 112",
    ),
    FieldSpec(
        name="gallery_locked",
        label="Выходы на рельсовые пути и галереи работающего мостового крана закрыты на замок",
        type="dropdown",
        group="Управление, сигнализация и связь",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 118",
    ),
    # ----------------------------- Крановый путь и противоугонные устройства
    FieldSpec(
        name="track_by_project",
        label="Рельсовый путь устроен по проекту, готовность подтверждена актом сдачи-приёмки",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 101, 203, подпункт «з» пункта 141",
    ),
    FieldSpec(
        name="rails_fastened",
        label="Рельсы закреплены так, что исключается их поперечный и продольный сдвиг",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 200",
    ),
    FieldSpec(
        name="end_stops_ok",
        label="Тупиковые упоры установлены и работоспособны",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=STATE,
        description=f"{FNP}, п. 259, подпункт «ф»",
    ),
    FieldSpec(
        name="anti_theft_ok",
        label="Противоугонные захваты установлены и работоспособны",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        options=STATE,
        description=f"{FNP}, п. 259, подпункт «у»",
    ),
    FieldSpec(
        name="track_deviations_ok",
        label="Отклонения рельсового пути в плане и профиле не превышают предельных величин",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, приложение № 5",
    ),
    FieldSpec(
        name="track_no_defects",
        label="Рельсовый путь без браковочных дефектов: трещин, смятия головки, уширения или сужения колеи",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        options=VERDICT,
        description=f"{FNP}, приложение № 3",
    ),
    FieldSpec(
        name="track_shift_check",
        label="Ежесменный осмотр рельсового пути крановщиком проводится, отметки имеются",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        options=VERDICT,
        description=f"{FNP}, пп. 206–207",
    ),
    FieldSpec(
        name="track_24_shifts_check",
        label="Осмотр пути после каждых 24 смен работы проведён под руководством ИТР с записью в журнал",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 208, 210",
    ),
    FieldSpec(
        name="track_annual_check",
        label="Плановая проверка рельсового пути проведена не реже 1 раза в 12 месяцев",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 209",
    ),
    FieldSpec(
        name="track_complex_survey",
        label="Комплексное обследование пути специализированной организацией проведено не реже 1 раза в 3 года",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 212–214",
    ),
    FieldSpec(
        name="parking_area_ok",
        label="Выделен участок для стоянки ПС в нерабочем состоянии",
        type="dropdown",
        group="Крановый путь и противоугонные устройства",
        options=VERDICT,
        description=f"{FNP}, п. 204",
    ),
    FieldSpec(
        name="last_track_survey",
        label="Дата последнего комплексного обследования рельсового пути",
        type="date",
        group="Крановый путь и противоугонные устройства",
    ),
    FieldSpec(
        name="track_deviation_value",
        label="Отклонение колеи по последней съёмке",
        type="number",
        group="Крановый путь и противоугонные устройства",
        unit="мм",
    ),
    # --------------------------------------- Электробезопасность и заземление
    FieldSpec(
        name="grounding_ok",
        label="Заземление ПС выполнено, сопротивление измерено и соответствует норме",
        type="dropdown",
        group="Электробезопасность и заземление",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «г»",
    ),
    FieldSpec(
        name="grounding_value",
        label="Сопротивление заземления ПС по последнему измерению",
        type="number",
        group="Электробезопасность и заземление",
        unit="Ом",
    ),
    FieldSpec(
        name="track_grounding_measured",
        label="При комплексном обследовании пути измерено сопротивление его заземления",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=VERDICT,
        description=f"{FNP}, пп. 212–214",
    ),
    FieldSpec(
        name="insulation_ok",
        label="Изоляция проводов и кабелей токоподвода не имеет повреждений",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=VERDICT,
        description=f"{FNP}, п. 170, подпункт «г»",
    ),
    FieldSpec(
        name="live_parts_guarded",
        label="Кабели и троллеи защищены от механических повреждений, токоведущие части ограждены",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=VERDICT,
    ),
    FieldSpec(
        name="phase_loss_protection",
        label="Защита от падения груза или стрелы при обрыве фазы работоспособна",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=VERDICT,
        description=f"{FNP}, п. 259, подпункт «с»",
    ),
    FieldSpec(
        name="interlocks_ok",
        label="Блокировки и координатная защита работоспособны",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=STATE,
        description=f"{FNP}, п. 259",
    ),
    FieldSpec(
        name="de_energized_ok",
        label="В нерабочем состоянии ПС обесточено, приняты меры против самопроизвольного включения",
        type="dropdown",
        group="Электробезопасность и заземление",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 122",
    ),
    FieldSpec(
        name="electrics_no_overheat",
        label="Электрооборудование без следов перегрева, оплавления и повреждения изоляции",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=STATE,
    ),
    FieldSpec(
        name="instruments_calibrated",
        label="Средства измерений поверены или калиброваны, срок не истёк",
        type="dropdown",
        group="Электробезопасность и заземление",
        options=VERDICT,
        description=f"{FNP}, п. 18",
    ),
    FieldSpec(
        name="last_grounding_test",
        label="Дата последнего измерения сопротивления заземления",
        type="date",
        group="Электробезопасность и заземление",
    ),
    # --------------------------- Осмотры, освидетельствование и персонал
    FieldSpec(
        name="survey_scope_defined",
        label="Объём, порядок и периодичность технических освидетельствований определены руководством по эксплуатации",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 164 — при отсутствии применяются нормы ФНП",
    ),
    FieldSpec(
        name="partial_survey_done",
        label="Частичное техническое освидетельствование проведено не реже 1 раза в 12 месяцев",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 165",
    ),
    FieldSpec(
        name="full_survey_done",
        label="Полное техническое освидетельствование проведено не реже 1 раза в 3 года",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=(
            f"{FNP}, п. 165 — для ПС при ремонте оборудования и обслуживании "
            "машинных залов допускается 1 раз в 5 лет"
        ),
    ),
    FieldSpec(
        name="extra_survey_done",
        label="Внеочередное полное освидетельствование проведено после монтажа, реконструкции или замены лебёдки",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description=f"{FNP}, п. 166",
    ),
    FieldSpec(
        name="survey_recorded",
        label="Результаты освидетельствования записаны в паспорт с указанием срока следующего",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 189",
    ),
    FieldSpec(
        name="maintenance_by_schedule",
        label="Техническое обслуживание и ремонт выполняются по графику ППР, записи в журнале ведутся",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description=f"{FNP}, п. 147",
    ),
    FieldSpec(
        name="inspections_logged",
        label="Результаты осмотров и технического обслуживания заносятся в вахтенный журнал",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description=f"{FNP}, п. 147",
    ),
    FieldSpec(
        name="building_structures_ok",
        label="Здания и подкрановые конструкции, воспринимающие нагрузки от ПС, не имеют недопустимых дефектов",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description=f"{FNP}, пп. 256–257",
    ),
    FieldSpec(
        name="epb_done",
        label="Экспертиза промышленной безопасности проведена в установленных случаях",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=(
            "Федеральный закон № 116-ФЗ, ст. 13 — при отсутствии сертификата "
            "соответствия или истёкшем сроке службы"
        ),
    ),
    FieldSpec(
        name="operator_certified",
        label="Крановщик обучен и имеет удостоверение с указанием типа ПС и видов работ",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=f"{FNP}, п. 151",
    ),
    FieldSpec(
        name="slinger_certified",
        label="Стропальщик имеет квалификацию и удостоверение",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        required=True,
        options=VERDICT,
        description=f"{FNP}, пп. 216–217",
    ),
    FieldSpec(
        name="ppe_provided",
        label="Работники обеспечены средствами индивидуальной защиты, при работе на высоте применяются системы защиты от падения",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description=(
            "Приказ Минтруда России от 29.10.2021 № 767н и "
            "приказ Минтруда России от 16.11.2020 № 782н"
        ),
    ),
    FieldSpec(
        name="safety_signs_ok",
        label="Знаки безопасности, ограждения опасных зон и сигнальная разметка установлены",
        type="dropdown",
        group="Осмотры, освидетельствование и персонал",
        options=VERDICT,
        description="ГОСТ 12.4.026-2015",
    ),
    FieldSpec(
        name="last_full_survey",
        label="Дата последнего полного технического освидетельствования",
        type="date",
        group="Осмотры, освидетельствование и персонал",
        required=True,
    ),
    FieldSpec(
        name="next_full_survey",
        label="Дата следующего полного технического освидетельствования",
        type="date",
        group="Осмотры, освидетельствование и персонал",
    ),
    # ------------------------------------------------------------ Заключение
    FieldSpec(
        name="condition_assessment",
        label="Оценка технического состояния подъёмного сооружения",
        type="dropdown",
        group="Заключение",
        required=True,
        options=ASSESSMENT,
    ),
    FieldSpec(
        name="defects_found",
        label="Выявленные несоответствия и дефекты",
        type="textarea",
        group="Заключение",
        placeholder="Перечень или «не выявлено»",
    ),
    FieldSpec(
        name="defects_critical",
        label="Дефекты, требующие немедленного устранения",
        type="textarea",
        group="Заключение",
        placeholder="Перечень или «не выявлено»",
    ),
    FieldSpec(
        name="repair_deadline",
        label="Срок устранения выявленных замечаний",
        type="date",
        group="Заключение",
    ),
    FieldSpec(
        name="operation_permission",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=PERMISSION,
    ),
    FieldSpec(
        name="conclusion",
        label="Вывод по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Краткий вывод",
    ),
]


if __name__ == "__main__":
    build_template(OUTPUT, GROUPS, FIELDS)
