"""Генератор шаблона проверки электроустановок.

Запуск (из корня проекта):

    python tools/build_electrical_template.py

Нормативная основа — ПУЭ, Правила технической эксплуатации электроустановок
потребителей электрической энергии (приказ Минэнерго России от 12.08.2022
№ 811), Правила по охране труда при эксплуатации электроустановок (приказ
Минтруда России от 15.12.2020 № 903н), ГОСТ Р 50571.16-2019.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "elektroustanovki.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
DONE = ("Выполнено", "Не выполнено", "Не требуется")
AVAIL = ("В наличии", "Отсутствует", "Частично")
YESNO = ("Да", "Нет")
ASSESSMENT = (
    "Исправно",
    "Работоспособно",
    "Ограниченно работоспособно",
    "Не работоспособно",
)
PERMISSION = ("Допускается", "Допускается с ограничениями", "Не допускается")

GROUPS = [
    "Общие сведения",
    "Документация и организация эксплуатации",
    "Заземление и защитные меры",
    "Кабельные линии и электропроводки",
    "Щиты и распределительные устройства",
    "Электродвигатели и приводы",
    "Освещение и розеточные сети",
    "Защита от перенапряжений и молниезащита",
    "Взрывозащищённое электрооборудование",
    "Безопасность работ",
    "Заключение",
]

FIELDS: list[FieldSpec] = [
    # --- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="ПАО «Газпром», ЛПУМГ, КС, цех",
        description="Организация и производственный объект",
    ),
    FieldSpec(
        name="installation_name",
        label="Наименование электроустановки",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="ВРУ-0,4 кВ, ТП-10/0,4 кВ, щит ЩС-3",
        description="Обозначение по однолинейной схеме",
    ),
    FieldSpec(
        name="voltage_class",
        label="Класс напряжения",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("До 1000 В", "Выше 1000 В", "Смешанная установка"),
        description="Определяет объём защитных мер и допуск персонала",
    ),
    FieldSpec(
        name="supply_system",
        label="Система заземления сети",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("TN-S", "TN-C", "TN-C-S", "TT", "IT"),
        description="ПУЭ глава 1.7, тип системы определяет защитные меры",
    ),
    FieldSpec(
        name="network_type",
        label="Род сети",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("Однофазная", "Трёхфазная", "Смешанная"),
        description="По проекту электроснабжения",
    ),
    FieldSpec(
        name="location_conditions",
        label="Условия размещения",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Отапливаемое помещение",
            "Неотапливаемое помещение",
            "Сырое помещение",
            "Особо сырое помещение",
            "Жаркое помещение",
            "Пыльное помещение",
            "На открытом воздухе",
            "Взрывоопасная зона",
        ),
        description="ПУЭ глава 1.1, влияет на степень защиты оболочек",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
    ),
    FieldSpec(
        name="inspection_type",
        label="Вид проверки",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Плановый осмотр",
            "Внеплановый осмотр",
            "ТО",
            "Периодические испытания и измерения",
            "После ремонта",
            "Приёмосдаточные испытания",
        ),
    ),
    FieldSpec(
        name="executor",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Петров П.П., электромонтёр",
        description="Лицо, проводившее проверку",
    ),
    FieldSpec(
        name="outdoor_temp",
        label="Температура окружающего воздуха",
        type="number",
        group="Общие сведения",
        placeholder="18",
        unit="°C",
    ),
    FieldSpec(
        name="regulatory_basis",
        label="Нормативная база проверки",
        type="text",
        group="Общие сведения",
        placeholder="ПУЭ, приказ Минэнерго № 811, приказ Минтруда № 903н",
    ),
    # --- Документация и организация эксплуатации
    FieldSpec(
        name="docs_schemes",
        label="Однолинейные схемы и схемы щитов",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=AVAIL,
        description="Приказ Минэнерго России от 12.08.2022 № 811",
    ),
    FieldSpec(
        name="docs_actual",
        label="Схемы соответствуют фактическому исполнению",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=VERDICT,
        description="Расхождение схем и фактического исполнения не допускается",
    ),
    FieldSpec(
        name="docs_passports",
        label="Паспорта и инструкции на электрооборудование",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=AVAIL,
    ),
    FieldSpec(
        name="docs_protocols",
        label="Протоколы предыдущих испытаний и измерений",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=AVAIL,
        description="Подтверждение периодичности испытаний",
    ),
    FieldSpec(
        name="responsible_person",
        label="Ответственный за электрохозяйство назначен",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=VERDICT,
        description="Приказ Минэнерго России от 12.08.2022 № 811",
    ),
    FieldSpec(
        name="staff_group",
        label="Группа по электробезопасности у персонала",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=("I", "II", "III", "IV", "V"),
        description="Приказ Минтруда России от 15.12.2020 № 903н",
    ),
    FieldSpec(
        name="journal_operational",
        label="Оперативный журнал ведётся",
        type="dropdown",
        group="Документация и организация эксплуатации",
        options=VERDICT,
    ),
    FieldSpec(
        name="journal_defects",
        label="Журнал дефектов и неполадок ведётся",
        type="dropdown",
        group="Документация и организация эксплуатации",
        options=VERDICT,
    ),
    FieldSpec(
        name="test_schedule",
        label="График испытаний и измерений утверждён",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="insulation_test_date",
        label="Дата последнего измерения сопротивления изоляции",
        type="date",
        group="Документация и организация эксплуатации",
    ),
    FieldSpec(
        name="grounding_test_date",
        label="Дата последнего измерения сопротивления заземления",
        type="date",
        group="Документация и организация эксплуатации",
    ),
    FieldSpec(
        name="loop_test_date",
        label="Дата последнего измерения петли «фаза-нуль»",
        type="date",
        group="Документация и организация эксплуатации",
    ),
    FieldSpec(
        name="ppe_available",
        label="Средства защиты и инструмент с изолирующими рукоятками",
        type="dropdown",
        group="Документация и организация эксплуатации",
        required=True,
        options=AVAIL,
        description="Приказ Минтруда России от 15.12.2020 № 903н",
    ),
    FieldSpec(
        name="ppe_test_date",
        label="Дата последних испытаний средств защиты",
        type="date",
        group="Документация и организация эксплуатации",
        description="Средства защиты подлежат периодическим испытаниям",
    ),
    FieldSpec(
        name="posters_signs",
        label="Знаки безопасности и плакаты",
        type="dropdown",
        group="Документация и организация эксплуатации",
        options=VERDICT,
    ),
    # --- Заземление и защитные меры
    FieldSpec(
        name="grounding_device",
        label="Заземляющее устройство",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=STATE,
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="grounding_measured",
        label="Сопротивление заземляющего устройства измерено",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=DONE,
        description="Периодичность по графику испытаний",
    ),
    FieldSpec(
        name="grounding_value",
        label="Измеренное сопротивление заземления",
        type="number",
        group="Заземление и защитные меры",
        placeholder="3,8",
        unit="Ом",
    ),
    FieldSpec(
        name="grounding_norm",
        label="Сопротивление не превышает нормируемое",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="ПУЭ глава 1.7, не более 4 Ом для электроустановок до 1000 В",
    ),
    FieldSpec(
        name="grounding_continuity",
        label="Непрерывность цепи заземления проверена",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="Металлосвязь корпусов с заземляющим устройством",
    ),
    FieldSpec(
        name="loop_value",
        label="Сопротивление петли «фаза-нуль»",
        type="number",
        group="Заземление и защитные меры",
        placeholder="0,4",
        unit="Ом",
    ),
    FieldSpec(
        name="loop_norm",
        label="Петля обеспечивает отключение защитным аппаратом",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="Ток КЗ должен превышать уставку автомата",
    ),
    FieldSpec(
        name="insulation_value",
        label="Сопротивление изоляции",
        type="number",
        group="Заземление и защитные меры",
        placeholder="20",
        unit="МОм",
    ),
    FieldSpec(
        name="insulation_norm",
        label="Сопротивление изоляции не менее 0,5 МОм",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="ГОСТ Р 50571.16-2019, цепи напряжением до 1000 В",
    ),
    FieldSpec(
        name="test_voltage",
        label="Напряжение мегаомметра при измерении",
        type="number",
        group="Заземление и защитные меры",
        placeholder="1000",
        unit="В",
    ),
    FieldSpec(
        name="neutral_grounding",
        label="Заземление нейтрали и повторное заземление",
        type="dropdown",
        group="Заземление и защитные меры",
        options=VERDICT,
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="grounding_conductors",
        label="Сечение и материал заземляющих проводников",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="Соответствие проекту и ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="grounding_connections",
        label="Соединения заземляющих проводников",
        type="dropdown",
        group="Заземление и защитные меры",
        options=VERDICT,
        description="Сварные и болтовые соединения, защита от коррозии",
    ),
    FieldSpec(
        name="grounding_marking",
        label="Маркировка PE-проводников",
        type="dropdown",
        group="Заземление и защитные меры",
        options=VERDICT,
        description="Жёлто-зелёная окраска или маркировка",
    ),
    FieldSpec(
        name="potential_bonding",
        label="Система уравнивания потенциалов",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
        description="ПУЭ глава 1.7, основная и дополнительная система",
    ),
    FieldSpec(
        name="metal_parts_grounding",
        label="Заземление металлических нетоковедущих частей",
        type="dropdown",
        group="Заземление и защитные меры",
        required=True,
        options=VERDICT,
    ),
    # --- Кабельные линии и электропроводки
    FieldSpec(
        name="cable_laying",
        label="Способ прокладки кабелей и проводов",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        required=True,
        options=("Открытая", "Скрытая", "В трубах", "В лотках", "В каналах", "В земле"),
        description="ПУЭ глава 2.1",
    ),
    FieldSpec(
        name="cable_integrity",
        label="Оболочка кабелей без повреждений",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="cable_insulation",
        label="Изоляция без трещин и следов перегрева",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_fastening",
        label="Крепление кабелей к конструкциям обеспечено",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_bend_radius",
        label="Радиусы изгиба соблюдены",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_junctions",
        label="Соединения выполнены в коробках, скруток нет",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        required=True,
        options=VERDICT,
        description="Скрутки не допускаются",
    ),
    FieldSpec(
        name="cable_marking",
        label="Маркировка кабелей и жил",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_entries",
        label="Вводы кабелей в оборудование уплотнены",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_penetrations",
        label="Герметизация проходов через стены и перекрытия",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_clearance",
        label="Расстояния до трубопроводов и нагретых поверхностей",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_protection",
        label="Механическая защита в местах возможных повреждений",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="wiring_boxes",
        label="Распределительные коробки закрыты и закреплены",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="wiring_devices",
        label="Выключатели и розетки закреплены, без повреждений",
        type="dropdown",
        group="Кабельные линии и электропроводки",
        options=VERDICT,
    ),
    FieldSpec(
        name="cable_defects",
        label="Выявленные дефекты кабельных линий",
        type="textarea",
        group="Кабельные линии и электропроводки",
        placeholder="Описание и место",
    ),
    # --- Щиты и распределительные устройства
    FieldSpec(
        name="panels_count",
        label="Количество щитов и распределительных устройств",
        type="number",
        group="Щиты и распределительные устройства",
        placeholder="4",
        unit="шт",
    ),
    FieldSpec(
        name="panel_enclosure",
        label="Корпуса щитов без повреждений, двери закрыты",
        type="dropdown",
        group="Щиты и распределительные устройства",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="panel_locking",
        label="Запирающие устройства и надписи на щитах",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=VERDICT,
    ),
    FieldSpec(
        name="panel_scheme_inside",
        label="Схема внутри щита соответствует фактической",
        type="dropdown",
        group="Щиты и распределительные устройства",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="panel_breakers",
        label="Автоматические выключатели",
        type="dropdown",
        group="Щиты и распределительные устройства",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="panel_ratings",
        label="Номиналы аппаратов защиты соответствуют проекту",
        type="dropdown",
        group="Щиты и распределительные устройства",
        required=True,
        options=VERDICT,
        description="Завышение номинала недопустимо",
    ),
    FieldSpec(
        name="panel_rcd",
        label="Устройства защитного отключения установлены",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=VERDICT,
        description="ПУЭ глава 7.1, защита от поражения током",
    ),
    FieldSpec(
        name="panel_rcd_test",
        label="Проверка УЗО кнопкой «Тест» выполнена",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=DONE,
    ),
    FieldSpec(
        name="panel_rcd_tested",
        label="Измеренные параметры срабатывания УЗО",
        type="text",
        group="Щиты и распределительные устройства",
        placeholder="30 мА, 25 мс",
        description="Ток и время срабатывания по протоколу",
    ),
    FieldSpec(
        name="panel_terminals",
        label="Контактные соединения затянуты, нагрева нет",
        type="dropdown",
        group="Щиты и распределительные устройства",
        required=True,
        options=VERDICT,
        description="ГОСТ 10434-82, соединения контактные электрические",
    ),
    FieldSpec(
        name="panel_thermal",
        label="Термографическое обследование проведено",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=DONE,
        description="При наличии приборов тепловизионного контроля",
    ),
    FieldSpec(
        name="panel_clean",
        label="Отсутствие пыли и посторонних предметов",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=VERDICT,
    ),
    FieldSpec(
        name="panel_dielectric",
        label="Диэлектрические коврики и средства защиты у щитов",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=AVAIL,
    ),
    FieldSpec(
        name="panel_labeling",
        label="Групповые надписи и маркировка аппаратов",
        type="dropdown",
        group="Щиты и распределительные устройства",
        options=VERDICT,
    ),
    # --- Электродвигатели и приводы
    FieldSpec(
        name="motors_count",
        label="Количество электродвигателей",
        type="number",
        group="Электродвигатели и приводы",
        placeholder="3",
        unit="шт",
    ),
    FieldSpec(
        name="motor_housing",
        label="Корпуса двигателей без повреждений, заземление выполнено",
        type="dropdown",
        group="Электродвигатели и приводы",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_terminals",
        label="Клеммные коробки закрыты, вводы уплотнены",
        type="dropdown",
        group="Электродвигатели и приводы",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_insulation",
        label="Сопротивление изоляции обмоток",
        type="number",
        group="Электродвигатели и приводы",
        placeholder="50",
        unit="МОм",
    ),
    FieldSpec(
        name="motor_insulation_norm",
        label="Сопротивление изоляции обмоток в норме",
        type="dropdown",
        group="Электродвигатели и приводы",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_cooling",
        label="Вентиляция и охлаждение обеспечены",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_bearings",
        label="Подшипники без постороннего шума и перегрева",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=STATE,
    ),
    FieldSpec(
        name="motor_vibration",
        label="Уровень вибрации в пределах нормы",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_protection",
        label="Защита от перегрузки и короткого замыкания настроена",
        type="dropdown",
        group="Электродвигатели и приводы",
        required=True,
        options=VERDICT,
    ),
    FieldSpec(
        name="motor_starters",
        label="Пусковая аппаратура (контакторы, пускатели)",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=STATE,
    ),
    FieldSpec(
        name="motor_control_circuits",
        label="Цепи управления и сигнализации работоспособны",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=STATE,
    ),
    FieldSpec(
        name="motor_interlocks",
        label="Блокировки и защита от самозапуска работоспособны",
        type="dropdown",
        group="Электродвигатели и приводы",
        options=VERDICT,
    ),
    # --- Освещение и розеточные сети
    FieldSpec(
        name="lighting_operability",
        label="Рабочее освещение работоспособно",
        type="dropdown",
        group="Освещение и розеточные сети",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="lighting_emergency",
        label="Аварийное и эвакуационное освещение работоспособно",
        type="dropdown",
        group="Освещение и розеточные сети",
        required=True,
        options=STATE,
    ),
    FieldSpec(
        name="lighting_fixtures",
        label="Светильники закреплены, без повреждений",
        type="dropdown",
        group="Освещение и розеточные сети",
        options=VERDICT,
    ),
    FieldSpec(
        name="lighting_protection",
        label="Степень защиты светильников соответствует среде",
        type="dropdown",
        group="Освещение и розеточные сети",
        options=VERDICT,
        description="ПУЭ глава 6.2, IP по условиям помещения",
    ),
    FieldSpec(
        name="sockets_condition",
        label="Розетки и выключатели без повреждений",
        type="dropdown",
        group="Освещение и розеточные сети",
        options=STATE,
    ),
    FieldSpec(
        name="sockets_protection",
        label="Розеточные группы защищены УЗО",
        type="dropdown",
        group="Освещение и розеточные сети",
        options=VERDICT,
        description="ПУЭ глава 7.1",
    ),
    FieldSpec(
        name="sockets_load",
        label="Нагрузка розеточных групп соответствует номиналу",
        type="dropdown",
        group="Освещение и розеточные сети",
        options=VERDICT,
    ),
    # --- Защита от перенапряжений и молниезащита
    FieldSpec(
        name="spd_present",
        label="Устройства защиты от импульсных перенапряжений (УЗИП)",
        type="dropdown",
        group="Защита от перенапряжений и молниезащита",
        options=AVAIL,
    ),
    FieldSpec(
        name="spd_state",
        label="Индикаторы УЗИП в норме",
        type="dropdown",
        group="Защита от перенапряжений и молниезащита",
        options=STATE,
    ),
    FieldSpec(
        name="spd_grounding",
        label="Заземление УЗИП выполнено",
        type="dropdown",
        group="Защита от перенапряжений и молниезащита",
        options=VERDICT,
    ),
    FieldSpec(
        name="lightning_protection",
        label="Молниеприёмники и токоотводы",
        type="dropdown",
        group="Защита от перенапряжений и молниезащита",
        options=STATE,
        description="СО 153-34.21.122-2003, устройство молниезащиты",
    ),
    FieldSpec(
        name="lightning_joints",
        label="Соединения токоотводов без обрывов",
        type="dropdown",
        group="Защита от перенапряжений и молниезащита",
        options=VERDICT,
    ),
    FieldSpec(
        name="lightning_value",
        label="Сопротивление заземлителя молниезащиты",
        type="number",
        group="Защита от перенапряжений и молниезащита",
        placeholder="8",
        unit="Ом",
    ),
    FieldSpec(
        name="lightning_test_date",
        label="Дата последней проверки молниезащиты",
        type="date",
        group="Защита от перенапряжений и молниезащита",
    ),
    # --- Взрывозащищённое электрооборудование
    FieldSpec(
        name="ex_marking",
        label="Маркировка взрывозащиты соответствует классу зоны",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=VERDICT,
        description="ПУЭ глава 7.3, ГОСТ IEC 60079-17-2011",
    ),
    FieldSpec(
        name="ex_enclosure",
        label="Оболочки без повреждений, степень защиты сохранена",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=STATE,
    ),
    FieldSpec(
        name="ex_cable_entries",
        label="Кабельные вводы уплотнены, заглушки установлены",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=VERDICT,
    ),
    FieldSpec(
        name="ex_grounding",
        label="Заземление корпусов Ex-оборудования",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=VERDICT,
    ),
    FieldSpec(
        name="ex_repairs",
        label="Ремонт выполнялся специализированной организацией",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=VERDICT,
    ),
    FieldSpec(
        name="ex_documentation",
        label="Сертификаты и документы на Ex-оборудование",
        type="dropdown",
        group="Взрывозащищённое электрооборудование",
        options=AVAIL,
    ),
    FieldSpec(
        name="ex_inspection_date",
        label="Дата последнего осмотра Ex-оборудования",
        type="date",
        group="Взрывозащищённое электрооборудование",
    ),
    # --- Безопасность работ
    FieldSpec(
        name="work_permit",
        label="Работы выполнялись по наряду-допуску или распоряжению",
        type="dropdown",
        group="Безопасность работ",
        required=True,
        options=VERDICT,
        description="Приказ Минтруда России от 15.12.2020 № 903н",
    ),
    FieldSpec(
        name="voltage_check",
        label="Проверка отсутствия напряжения выполнена",
        type="dropdown",
        group="Безопасность работ",
        options=DONE,
    ),
    FieldSpec(
        name="portable_grounding",
        label="Переносное заземление применено",
        type="dropdown",
        group="Безопасность работ",
        options=DONE,
    ),
    FieldSpec(
        name="ppe_used",
        label="Средства защиты применены",
        type="dropdown",
        group="Безопасность работ",
        options=DONE,
    ),
    FieldSpec(
        name="insulated_tools",
        label="Инструмент с изолирующими рукоятками",
        type="dropdown",
        group="Безопасность работ",
        options=VERDICT,
    ),
    FieldSpec(
        name="warning_signs",
        label="Плакаты и знаки безопасности выставлены",
        type="dropdown",
        group="Безопасность работ",
        options=DONE,
    ),
    FieldSpec(
        name="first_aid",
        label="Аптечка и средства оказания первой помощи",
        type="dropdown",
        group="Безопасность работ",
        options=AVAIL,
    ),
    FieldSpec(
        name="fire_safety",
        label="Средства пожаротушения в наличии и проверены",
        type="dropdown",
        group="Безопасность работ",
        options=AVAIL,
    ),
    # --- Заключение
    FieldSpec(
        name="defects_found",
        label="Выявленные дефекты и несоответствия",
        type="textarea",
        group="Заключение",
        required=True,
        placeholder="Перечень с указанием мест",
    ),
    FieldSpec(
        name="defects_critical",
        label="Дефекты, требующие немедленного устранения",
        type="textarea",
        group="Заключение",
        placeholder="Перечень критичных дефектов",
    ),
    FieldSpec(
        name="work_performed",
        label="Работы, выполненные при проверке",
        type="textarea",
        group="Заключение",
        placeholder="Подтяжка контактов, замена ламп, чистка щитов",
    ),
    FieldSpec(
        name="condition_assessment",
        label="Оценка технического состояния электроустановки",
        type="dropdown",
        group="Заключение",
        required=True,
        options=ASSESSMENT,
    ),
    FieldSpec(
        name="operation_permission",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=PERMISSION,
    ),
    FieldSpec(
        name="repair_required",
        label="Требуется ремонт или замена",
        type="dropdown",
        group="Заключение",
        options=YESNO,
    ),
    FieldSpec(
        name="repair_deadline",
        label="Срок устранения замечаний",
        type="date",
        group="Заключение",
    ),
    FieldSpec(
        name="next_check_date",
        label="Дата следующей проверки",
        type="date",
        group="Заключение",
        required=True,
    ),
    FieldSpec(
        name="recommendation",
        label="Рекомендации по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Мероприятия по устранению замечаний",
    ),
    FieldSpec(
        name="approver",
        label="Проверку согласовал (ФИО, должность)",
        type="text",
        group="Заключение",
        placeholder="Иванов И.И., главный энергетик",
    ),
    FieldSpec(
        name="notes",
        label="Примечания",
        type="textarea",
        group="Заключение",
        placeholder="Дополнительная информация",
    ),
]


def main() -> None:
    build_template(OUTPUT, GROUPS, FIELDS)


if __name__ == "__main__":
    main()
