"""Генератор шаблона проверки КИП кранового узла магистрального газопровода.

Запуск (из корня проекта):

    python tools/build_kip_template.py

"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:  # pragma: no cover - зависит от запуска
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.template_builder import FieldSpec, build_template  # noqa: E402

OUTPUT = PROJECT_ROOT / "templates" / "kip_kranovyy_uzel_mg.csv"

# --- наборы вариантов ответа -------------------------------------------------

VERDICT = ("Соответствует", "Не соответствует", "Не применимо")
STATE = ("Исправно", "Неисправно", "Не применимо")
DONE = ("Выполнено", "Не выполнено", "Не требуется")
AVAIL = ("В наличии", "Отсутствует", "Частично")

GROUPS = [
    "Общие сведения",
    "Документация и метрология",
    "Датчики и преобразователи",
    "Манометры",
    "Импульсные и трубные проводки",
    "Соединительные коробки",
    "Кабельные линии",
    "Заземление и взрывозащита",
    "Функциональная проверка",
    "Заключение",
]


FIELDS: list[FieldSpec] = [
    # --- Общие сведения
    FieldSpec(
        name="object_name",
        label="Наименование объекта",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="ПАО «Газпром», ЛПУМГ, КС",
        description="Организация и производственный объект",
    ),
    FieldSpec(
        name="pipeline",
        label="Магистральный газопровод",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="МГ «...», DN 1400, Ру 7,4 МПа",
        description="Наименование, диаметр и условное давление",
    ),
    FieldSpec(
        name="crane_unit_no",
        label="Номер кранового узла",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="КУ-14",
        description="Обозначение по проекту и технологической схеме",
    ),
    FieldSpec(
        name="km_axis",
        label="Километр и привязка к трассе",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="142 км + 350 м",
        description="Пикетажное положение узла",
    ),
    FieldSpec(
        name="crane_type",
        label="Тип крана",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("Шаровой", "Клиновой", "Задвижка", "Регулирующий", "Обратный"),
        description="Вид запорной арматуры узла",
    ),
    FieldSpec(
        name="crane_dn",
        label="Номинальный диаметр DN",
        type="number",
        group="Общие сведения",
        placeholder="1400",
        description="По паспорту арматуры",
        unit="мм",
    ),
    FieldSpec(
        name="crane_pn",
        label="Номинальное давление PN",
        type="number",
        group="Общие сведения",
        placeholder="7,4",
        description="По паспорту арматуры",
        unit="МПа",
    ),
    FieldSpec(
        name="work_pressure",
        label="Рабочее давление газа при проверке",
        type="number",
        group="Общие сведения",
        required=True,
        placeholder="5,4",
        description="Давление в момент осмотра по штатному манометру",
        unit="МПа",
    ),
    FieldSpec(
        name="inspection_date",
        label="Дата проверки",
        type="date",
        group="Общие сведения",
        required=True,
        description="Дата фактического проведения работ",
    ),
    FieldSpec(
        name="inspection_time",
        label="Время начала проверки",
        type="time",
        group="Общие сведения",
        placeholder="09:30",
        description="Время начала работ на узле",
    ),
    FieldSpec(
        name="inspection_type",
        label="Вид проверки",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=(
            "Плановый осмотр",
            "ТО-1",
            "ТО-2",
            "Сезонное обслуживание",
            "Внеплановый",
            "После ремонта",
            "Комплексное диагностирование",
        ),
        description="Основание для проведения работ",
    ),
    FieldSpec(
        name="executor",
        label="Проверку выполнил (ФИО, должность)",
        type="text",
        group="Общие сведения",
        required=True,
        placeholder="Иванов И.И., инженер КИПиА",
        description="Лицо, проводившее проверку",
    ),
    FieldSpec(
        name="outdoor_temp",
        label="Температура наружного воздуха",
        type="number",
        group="Общие сведения",
        placeholder="12",
        description="Условия проведения проверки",
        unit="°C",
    ),
    FieldSpec(
        name="weather",
        label="Погодные условия",
        type="text",
        group="Общие сведения",
        placeholder="Ясно, ветер 3 м/с",
        description="Осадки, ветер, видимость",
    ),
    FieldSpec(
        name="kip_system",
        label="Тип системы КИПиА",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("Пневматическая", "Электрическая", "Микропроцессорная", "Смешанная"),
        description="Принцип действия средств автоматизации узла",
    ),
    FieldSpec(
        name="explosion_zone",
        label="Класс взрывоопасной зоны по ПУЭ",
        type="dropdown",
        group="Общие сведения",
        required=True,
        options=("В-I", "В-Iа", "В-Iб", "В-Iг", "В-II", "В-IIа", "Не взрывоопасная"),
        description="Глава 7.3 ПУЭ, по проекту",
    ),
    FieldSpec(
        name="regulatory_basis",
        label="Нормативная база проверки",
        type="text",
        group="Общие сведения",
        description="ФНП № 534 и № 536, ВРД 39-1.10-006-2000, ГОСТ IEC 60079-17-2011",
    ),
    # --- Документация и метрология
    FieldSpec(
        name="docs_project",
        label="Проектная документация на КИПиА узла",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("В наличии", "Отсутствует", "Частично"),
        description="Наличие и комплектность проектной документации",
    ),
    FieldSpec(
        name="docs_schemes",
        label="Принципиальные и монтажные схемы КИПиА",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("В наличии", "Отсутствует", "Частично"),
        description="Схемы соответствуют фактическому исполнению",
    ),
    FieldSpec(
        name="docs_passports",
        label="Паспорта и формуляры на СИ и оборудование КИПиА",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("В наличии", "Отсутствует", "Частично"),
        description="Наличие заводской документации",
    ),
    FieldSpec(
        name="docs_verification",
        label="Действующие свидетельства о поверке СИ",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("В наличии", "Отсутствует", "Частично"),
        description="Приказ Минпромторга России от 31.07.2020 № 2510",
    ),
    FieldSpec(
        name="verification_expiry",
        label="Ближайшая дата окончания поверки СИ",
        type="date",
        group="Документация и метрология",
        required=True,
        description="Контроль межповерочного интервала",
    ),
    FieldSpec(
        name="arshin_record",
        label="Сведения о поверке внесены в ФГИС «Аршин»",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Приказ Минпромторга России от 31.07.2020 № 2510",
    ),
    FieldSpec(
        name="calibration_interval",
        label="Периодичность поверки по описанию типа СИ",
        type="text",
        group="Документация и метрология",
        placeholder="12",
        description="Межповерочный интервал",
        unit="мес",
    ),
    FieldSpec(
        name="accuracy_class_check",
        label="Класс точности СИ соответствует проекту и ГОСТ 8.401-80",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 8.401-80, проектные требования",
    ),
    FieldSpec(
        name="metrology_service",
        label="СИ закреплены за метрологической службой",
        type="dropdown",
        group="Документация и метрология",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ Р 8.596-2002, организационный порядок",
    ),
    FieldSpec(
        name="journal_control",
        label="Ведение журнала контрольных проверок манометров",
        type="dropdown",
        group="Документация и метрология",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ФНП № 536 от 15.12.2020, форма и полнота записей",
    ),
    FieldSpec(
        name="journal_last_date",
        label="Дата последней записи в журнале контрольных проверок",
        type="date",
        group="Документация и метрология",
        description="ФНП № 536: проверка контрольным манометром не реже 1 раза в 6 месяцев",
    ),
    FieldSpec(
        name="maintenance_schedule",
        label="Утверждённый график ТО и ремонта средств КИПиА",
        type="dropdown",
        group="Документация и метрология",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ВРД 39-1.10-006-2000, организация ТО",
    ),
    FieldSpec(
        name="defects_log",
        label="Записи о дефектах КИПиА соответствуют фактическому состоянию",
        type="dropdown",
        group="Документация и метрология",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Достоверность эксплуатационной документации",
    ),
    # --- Датчики и преобразователи
    FieldSpec(
        name="sensors_total",
        label="Количество датчиков на узле",
        type="number",
        group="Датчики и преобразователи",
        placeholder="8",
        description="Фактическое количество по проекту",
        unit="шт",
    ),
    FieldSpec(
        name="sensor_pressure",
        label="Датчики давления (до и после крана, в контуре)",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Основные первичные преобразователи узла",
    ),
    FieldSpec(
        name="sensor_pressure_list",
        label="Перечень датчиков давления",
        type="textarea",
        group="Датчики и преобразователи",
        placeholder="Позиция, тип, зав. №, диапазон",
        description="Позиционные обозначения по ГОСТ 21.404-85",
    ),
    FieldSpec(
        name="sensor_temperature",
        label="Датчики температуры",
        type="dropdown",
        group="Датчики и преобразователи",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Контроль температуры газа и окружающей среды",
    ),
    FieldSpec(
        name="sensor_dp",
        label="Датчики перепада давления",
        type="dropdown",
        group="Датчики и преобразователи",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Контроль фильтров и расхода",
    ),
    FieldSpec(
        name="sensor_gas",
        label="Датчики загазованности по метану",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Контроль загазованности в помещениях и на площадке",
    ),
    FieldSpec(
        name="sensor_position",
        label="Датчики и конечные выключатели положения крана",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Контроль крайних положений запорной арматуры",
    ),
    FieldSpec(
        name="sensor_ex_marking",
        label="Маркировка взрывозащиты датчиков соответствует проекту и классу зоны",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014, ПУЭ глава 7.3",
    ),
    FieldSpec(
        name="sensor_ex_value",
        label="Фактическая маркировка взрывозащиты датчиков",
        type="text",
        group="Датчики и преобразователи",
        placeholder="Ex ia IIC T4 Ga",
        description="Маркировка с таблички датчика",
    ),
    FieldSpec(
        name="sensor_enclosure",
        label="Корпуса датчиков без повреждений, коррозии и загрязнений",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, визуальный осмотр",
    ),
    FieldSpec(
        name="sensor_cable_entry",
        label="Кабельные вводы уплотнены, неиспользуемые заглушены",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, сохранение вида взрывозащиты",
    ),
    FieldSpec(
        name="sensor_grounding",
        label="Заземление корпусов датчиков",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7, проектные решения",
    ),
    FieldSpec(
        name="sensor_range",
        label="Диапазон измерений соответствует проекту и рабочему давлению",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ Р 8.596-2002, проверка по паспорту",
    ),
    FieldSpec(
        name="sensor_seals",
        label="Пломбы и знаки поверки не нарушены",
        type="dropdown",
        group="Датчики и преобразователи",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Приказ Минпромторга России от 31.07.2020 № 2510",
    ),
    FieldSpec(
        name="sensor_check_date",
        label="Дата последней поверки (калибровки) датчика",
        type="date",
        group="Датчики и преобразователи",
        description="По свидетельству о поверке",
    ),
    FieldSpec(
        name="sensor_reading_compare",
        label="Показания сверены с контрольным прибором",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="ГОСТ Р 8.596-2002, контроль метрологических характеристик",
    ),
    FieldSpec(
        name="sensor_deviation",
        label="Расхождение показаний с контрольным прибором",
        type="number",
        group="Датчики и преобразователи",
        placeholder="0,4",
        description="Приведённое расхождение",
        unit="%",
    ),
    FieldSpec(
        name="sensor_deviation_norm",
        label="Отклонение не превышает предела допускаемой погрешности",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 8.401-80, по классу точности прибора",
    ),
    FieldSpec(
        name="sensor_valves",
        label="Запорные и продувочные вентили датчиков",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Обеспечение отключения и продувки",
    ),
    FieldSpec(
        name="sensor_separator",
        label="Разделительные сосуды и дренажные устройства",
        type="dropdown",
        group="Датчики и преобразователи",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Защита датчиков от агрессивной среды",
    ),
    FieldSpec(
        name="sensor_mounting",
        label="Крепление датчиков надёжное, вибрация отсутствует",
        type="dropdown",
        group="Датчики и преобразователи",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Отсутствие дополнительных нагрузок на прибор",
    ),
    FieldSpec(
        name="sensor_tagging",
        label="Маркировка и позиционные обозначения сохранены",
        type="dropdown",
        group="Датчики и преобразователи",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 21.404-85",
    ),
    # --- Манометры
    FieldSpec(
        name="manometers_total",
        label="Количество манометров на узле",
        type="number",
        group="Манометры",
        placeholder="6",
        description="Фактическое количество",
        unit="шт",
    ),
    FieldSpec(
        name="manometer_accuracy",
        label="Класс точности не ниже 2,5 при рабочем давлении до 2,5 МПа",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ФНП № 536 от 15.12.2020, ГОСТ 2405-88",
    ),
    FieldSpec(
        name="manometer_scale",
        label="Стрелка при рабочем давлении находится во второй трети шкалы",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ФНП № 536 от 15.12.2020",
    ),
    FieldSpec(
        name="manometer_red_mark",
        label="Красная черта (метка) по разрешённому давлению нанесена",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ФНП № 536 от 15.12.2020",
    ),
    FieldSpec(
        name="manometer_condition",
        label="Корпус, стекло и циферблат без повреждений, шкала читается",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ГОСТ 2405-88, общие технические требования",
    ),
    FieldSpec(
        name="manometer_pointer",
        label="Стрелка перемещается плавно, без заеданий",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ГОСТ 2405-88, проверка работоспособности",
    ),
    FieldSpec(
        name="manometer_three_way",
        label="Трёхходовой кран (запорный вентиль) исправен",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ФНП № 536 от 15.12.2020",
    ),
    FieldSpec(
        name="manometer_zero_check",
        label="Проверка исправности установкой стрелки на нуль",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="ФНП № 536 от 15.12.2020, трёхходовым краном или запорным вентилем",
    ),
    FieldSpec(
        name="manometer_siphon",
        label="Сифонная (петлеобразная) трубка установлена и исправна",
        type="dropdown",
        group="Манометры",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Защита манометра от температуры среды",
    ),
    FieldSpec(
        name="manometer_control_date",
        label="Дата последней проверки контрольным манометром",
        type="date",
        group="Манометры",
        description="ФНП № 536 от 15.12.2020, запись в журнале",
    ),
    FieldSpec(
        name="manometer_control_period",
        label="Проверка контрольным манометром выполнена не реже 1 раза в 6 месяцев",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ФНП № 536 от 15.12.2020, с записью в журнале",
    ),
    FieldSpec(
        name="manometer_control_device",
        label="Применённый контрольный манометр",
        type="text",
        group="Манометры",
        placeholder="МП4-У, зав. № 1234",
        description="Тип и заводской номер контрольного прибора",
    ),
    FieldSpec(
        name="manometer_verification",
        label="Срок поверки не истёк, знак поверки в наличии",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Приказ Минпромторга России от 31.07.2020 № 2510",
    ),
    FieldSpec(
        name="manometer_connection",
        label="Присоединение к импульсной линии герметично",
        type="dropdown",
        group="Манометры",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Отсутствие утечек в месте отбора",
    ),
    FieldSpec(
        name="manometer_lighting",
        label="Освещённость шкалы достаточна для считывания",
        type="dropdown",
        group="Манометры",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Условия эксплуатации и охраны труда",
    ),
    FieldSpec(
        name="manometer_list",
        label="Перечень манометров узла",
        type="textarea",
        group="Манометры",
        placeholder="Позиция, зав. №, диапазон, класс",
        description="Сводные данные по всем манометрам",
    ),
    # --- Импульсные и трубные проводки
    FieldSpec(
        name="tubing_material",
        label="Материал, диаметр и толщина стенки проводок соответствуют проекту",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Проектные решения по импульсным линиям и трубным проводкам",
    ),
    FieldSpec(
        name="tubing_integrity",
        label="Целостность проводок: трещин, разрывов и вмятин нет",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Визуальный и измерительный контроль",
    ),
    FieldSpec(
        name="tubing_joints",
        label="Резьбовые и сварные соединения герметичны",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Проверка плотности импульсных линий и трубных проводок",
    ),
    FieldSpec(
        name="tubing_leak_method",
        label="Метод проверки герметичности",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Обмыливание", "Течеискатель", "Опрессовка", "Визуальный осмотр"),
        description="Применённый способ контроля плотности",
    ),
    FieldSpec(
        name="tubing_test_pressure",
        label="Давление при проверке плотности",
        type="number",
        group="Импульсные и трубные проводки",
        placeholder="5,4",
        description="Давление контрольной опрессовки",
        unit="МПа",
    ),
    FieldSpec(
        name="tubing_slope",
        label="Уклон обеспечен в сторону дренажа или отбора",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Исключение скопления конденсата в линиях",
    ),
    FieldSpec(
        name="tubing_purge",
        label="Продувка линий выполнена",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="Удаление конденсата и механических примесей",
    ),
    FieldSpec(
        name="tubing_valves",
        label="Запорная, продувочная и дренажная арматура и устройства",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Работоспособность арматуры, дренажей и продувочных устройств",
    ),
    FieldSpec(
        name="tubing_supports",
        label="Крепления и опоры без ослабления, шаг соответствует проекту",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Исключение вибрации и деформаций",
    ),
    FieldSpec(
        name="tubing_corrosion",
        label="Коррозия, механические повреждения и деформации отсутствуют",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Контроль состояния металла проводок",
    ),
    FieldSpec(
        name="tubing_coating",
        label="Антикоррозионное покрытие и окраска не повреждены",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Защита от коррозии",
    ),
    FieldSpec(
        name="tubing_heating",
        label="Обогрев и теплоизоляция исправны (при наличии)",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Защита от замерзания конденсата",
    ),
    FieldSpec(
        name="tubing_vibration",
        label="Защита от вибрации обеспечена",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ВРД 39-1.10-006-2000, эксплуатационные требования",
    ),
    FieldSpec(
        name="tubing_clearance",
        label="Контакт с нагретыми поверхностями и кабелями отсутствует",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Недопустимость теплового воздействия на линии",
    ),
    FieldSpec(
        name="tubing_vent",
        label="Свечи продувки и дренажи выведены в безопасное место",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Требования промышленной безопасности",
    ),
    FieldSpec(
        name="tubing_sagging",
        label="Провисания и деформации отсутствуют",
        type="dropdown",
        group="Импульсные и трубные проводки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Контроль пространственного положения проводок",
    ),
    FieldSpec(
        name="tubing_marking",
        label="Маркировка проводок и арматуры сохранена",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Читаемость обозначений по проекту",
    ),
    FieldSpec(
        name="tubing_grounding",
        label="Заземление металлических проводок выполнено (при необходимости)",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="tubing_connectors",
        label="Соединения выполнены по проекту, детали не заменялись",
        type="dropdown",
        group="Импульсные и трубные проводки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Недопустимость произвольной замены элементов",
    ),
    FieldSpec(
        name="tubing_defects",
        label="Выявленные дефекты проводок",
        type="textarea",
        group="Импульсные и трубные проводки",
        placeholder="Описание и место",
        description="Подробное описание для устранения",
    ),
    # --- Соединительные коробки
    FieldSpec(
        name="jb_total",
        label="Количество соединительных коробок",
        type="number",
        group="Соединительные коробки",
        placeholder="4",
        description="Фактическое количество на узле",
        unit="шт",
    ),
    FieldSpec(
        name="jb_ex_marking",
        label="Маркировка взрывозащиты соответствует проекту и классу зоны",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, ГОСТ 31610.11-2014",
    ),
    FieldSpec(
        name="jb_enclosure",
        label="Корпуса без трещин, сколов и следов коррозии",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, визуальный осмотр",
    ),
    FieldSpec(
        name="jb_sealing",
        label="Уплотнения крышек и кабельных вводов в исправности",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Сохранение степени защиты и вида взрывозащиты",
    ),
    FieldSpec(
        name="jb_plugs",
        label="Неиспользуемые вводы заглушены взрывозащищёнными заглушками",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011",
    ),
    FieldSpec(
        name="jb_moisture",
        label="Внутри отсутствуют влага, конденсат и пыль",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Контроль состояния изоляции и контактов",
    ),
    FieldSpec(
        name="jb_terminals",
        label="Клеммные соединения затянуты, окисления и нагрева нет",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, детальный осмотр",
    ),
    FieldSpec(
        name="jb_marking",
        label="Маркировка коробок и подходящих кабелей читается",
        type="dropdown",
        group="Соединительные коробки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Эксплуатационная документация",
    ),
    FieldSpec(
        name="jb_grounding",
        label="Заземление корпусов коробок",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="jb_is_separation",
        label="Искробезопасные цепи отделены от силовых цепей",
        type="dropdown",
        group="Соединительные коробки",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014, требование разделения цепей",
    ),
    FieldSpec(
        name="jb_barrier_grounding",
        label="Барьеры искрозащиты заземлены",
        type="dropdown",
        group="Соединительные коробки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014, монтаж искробезопасных цепей",
    ),
    FieldSpec(
        name="jb_ip_rating",
        label="Степень защиты оболочек соответствует условиям эксплуатации",
        type="dropdown",
        group="Соединительные коробки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Проектные требования, условия наружной установки",
    ),
    FieldSpec(
        name="jb_cable_reserve",
        label="Запас кабеля и радиусы изгиба соблюдены",
        type="dropdown",
        group="Соединительные коробки",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Исключение натяжения жил и вводов",
    ),
    # --- Кабельные линии
    FieldSpec(
        name="cables_total",
        label="Количество кабельных линий КИПиА",
        type="number",
        group="Кабельные линии",
        placeholder="12",
        description="Фактическое количество",
        unit="шт",
    ),
    FieldSpec(
        name="cable_sheath",
        label="Оболочка кабелей без механических повреждений",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, визуальный осмотр",
    ),
    FieldSpec(
        name="cable_insulation_measured",
        label="Сопротивление изоляции измерено мегаомметром",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="ПУЭ, ПТЭЭП, периодические испытания",
    ),
    FieldSpec(
        name="cable_insulation_value",
        label="Измеренное сопротивление изоляции",
        type="number",
        group="Кабельные линии",
        placeholder="20",
        description="Наихудшее значение по результатам измерений",
        unit="МОм",
    ),
    FieldSpec(
        name="cable_insulation_norm",
        label="Сопротивление изоляции не менее 0,5 МОм",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Норма для цепей напряжением до 1000 В",
    ),
    FieldSpec(
        name="cable_test_voltage",
        label="Напряжение мегаомметра при измерении",
        type="number",
        group="Кабельные линии",
        placeholder="1000",
        description="Для цепей до 1000 В применяется мегаомметр на 1000 В",
        unit="В",
    ),
    FieldSpec(
        name="cable_grounding",
        label="Заземление брони и экранов кабелей",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7",
    ),
    FieldSpec(
        name="cable_trays",
        label="Лотки, трубы и металлорукава без повреждений",
        type="dropdown",
        group="Кабельные линии",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Состояние кабельных сооружений",
    ),
    FieldSpec(
        name="cable_entry_sealing",
        label="Вводы кабелей в оборудование герметизированы",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Сохранение взрывозащиты и степени защиты",
    ),
    FieldSpec(
        name="cable_marking",
        label="Маркировка кабелей и жил на обоих концах",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Эксплуатационная документация",
    ),
    FieldSpec(
        name="cable_separation",
        label="Раздельная прокладка искробезопасных и силовых цепей",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014",
    ),
    FieldSpec(
        name="cable_bend_radius",
        label="Радиусы изгиба и запас кабеля соблюдены",
        type="dropdown",
        group="Кабельные линии",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Исключение повреждения изоляции",
    ),
    FieldSpec(
        name="cable_fastening",
        label="Крепление кабелей к лоткам и конструкциям обеспечено",
        type="dropdown",
        group="Кабельные линии",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Исключение провисания и натяжения",
    ),
    FieldSpec(
        name="cable_overheating",
        label="Следы перегрева и оплавления изоляции отсутствуют",
        type="dropdown",
        group="Кабельные линии",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Признаки недопустимых токовых нагрузок",
    ),
    FieldSpec(
        name="cable_is_parameters",
        label="Ёмкость и индуктивность искробезопасной цепи в пределах допустимых",
        type="dropdown",
        group="Кабельные линии",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014, проверка параметров цепи",
    ),
    FieldSpec(
        name="cable_defects",
        label="Выявленные дефекты кабельных линий",
        type="textarea",
        group="Кабельные линии",
        placeholder="Описание и место",
        description="Подробное описание для устранения",
    ),
    # --- Заземление и взрывозащита
    FieldSpec(
        name="grounding_measured",
        label="Сопротивление заземляющего устройства измерено",
        type="dropdown",
        group="Заземление и взрывозащита",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="ПУЭ глава 1.7, периодические испытания",
    ),
    FieldSpec(
        name="grounding_value",
        label="Измеренное сопротивление заземления",
        type="number",
        group="Заземление и взрывозащита",
        placeholder="3,8",
        description="Наибольшее значение по результатам измерений",
        unit="Ом",
    ),
    FieldSpec(
        name="grounding_norm",
        label="Сопротивление не превышает нормируемое значение",
        type="dropdown",
        group="Заземление и взрывозащита",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7, не более 4 Ом для электроустановок до 1000 В",
    ),
    FieldSpec(
        name="grounding_measure_date",
        label="Дата последнего измерения сопротивления заземления",
        type="date",
        group="Заземление и взрывозащита",
        description="По протоколу измерений",
    ),
    FieldSpec(
        name="grounding_continuity",
        label="Непрерывность цепи заземления проверена",
        type="dropdown",
        group="Заземление и взрывозащита",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7, металлосвязь корпусов с ЗУ",
    ),
    FieldSpec(
        name="grounding_joints",
        label="Соединения заземляющих проводников надёжны и промаркированы",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7, требования к соединениям",
    ),
    FieldSpec(
        name="lightning_protection",
        label="Устройства молниезащиты исправны, токоотводы целы",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Проектные решения по молниезащите",
    ),
    FieldSpec(
        name="ex_compliance",
        label="Электрооборудование соответствует классу взрывоопасной зоны",
        type="dropdown",
        group="Заземление и взрывозащита",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 7.3, ГОСТ IEC 60079-17-2011",
    ),
    FieldSpec(
        name="ex_certificates",
        label="Сертификаты и маркировка взрывозащиты в наличии",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("В наличии", "Отсутствует", "Частично"),
        description="Подтверждение вида взрывозащиты",
    ),
    FieldSpec(
        name="ex_repair",
        label="Ремонт Ex-оборудования выполнялся специализированной организацией",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ IEC 60079-17-2011, требования к ремонту",
    ),
    FieldSpec(
        name="ex_intrinsic_params",
        label="Параметры искробезопасных цепей соответствуют ГОСТ 31610.11-2014",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ГОСТ 31610.11-2014",
    ),
    FieldSpec(
        name="equipotential_bonding",
        label="Уравнивание потенциалов выполнено",
        type="dropdown",
        group="Заземление и взрывозащита",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="ПУЭ глава 1.7",
    ),
    # --- Функциональная проверка
    FieldSpec(
        name="func_signal_path",
        label="Прохождение сигналов от датчиков до системы телемеханики проверено",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="Проверка канала измерения целиком",
    ),
    FieldSpec(
        name="func_setpoints",
        label="Уставки сигнализации и защит проверены",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="ВРД 39-1.10-006-2000, проверка настроек",
    ),
    FieldSpec(
        name="func_alarm",
        label="Срабатывание световой и звуковой сигнализации проверено",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="Проверка средств оповещения",
    ),
    FieldSpec(
        name="func_telemetry",
        label="Канал телемеханики в работе, отказов нет",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="Связь с диспетчерским пунктом",
    ),
    FieldSpec(
        name="func_data_match",
        label="Значения в системе соответствуют показаниям приборов",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="Достоверность передаваемых данных",
    ),
    FieldSpec(
        name="func_setpoint_values",
        label="Проверенные значения уставок",
        type="textarea",
        group="Функциональная проверка",
        placeholder="Параметр, уставка, фактическое срабатывание",
        description="Протокол проверки уставок",
    ),
    FieldSpec(
        name="func_power",
        label="Основное и резервное питание КИПиА в норме",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Исправно", "Неисправно", "Не применимо"),
        description="ПУЭ, требования к электропитанию",
    ),
    FieldSpec(
        name="func_ups",
        label="Резервный источник питания проверен под нагрузкой",
        type="dropdown",
        group="Функциональная проверка",
        options=("Выполнено", "Не выполнено", "Не требуется"),
        description="Проверка работоспособности АКБ и ИБП",
    ),
    FieldSpec(
        name="func_valve_time",
        label="Время перестановки крана в пределах нормы",
        type="dropdown",
        group="Функциональная проверка",
        options=("Соответствует", "Не соответствует", "Не применимо"),
        description="По паспорту арматуры и проекту",
    ),
    FieldSpec(
        name="valve_time_value",
        label="Измеренное время перестановки крана",
        type="number",
        group="Функциональная проверка",
        placeholder="45",
        description="Фактическое время срабатывания",
        unit="с",
    ),
    FieldSpec(
        name="func_failures",
        label="Отказы и ошибки связи за межпроверочный период",
        type="textarea",
        group="Функциональная проверка",
        placeholder="Дата, характер, принятые меры",
        description="Анализ надёжности работы",
    ),
    FieldSpec(
        name="func_result",
        label="Результат функциональной проверки",
        type="dropdown",
        group="Функциональная проверка",
        required=True,
        options=("Работоспособно", "Работоспособно с замечаниями", "Не работоспособно"),
        description="Итоговая оценка работоспособности",
    ),
    # --- Заключение
    FieldSpec(
        name="defects_found",
        label="Выявленные дефекты и несоответствия",
        type="textarea",
        group="Заключение",
        required=True,
        placeholder="Перечень с указанием мест",
        description="Описание всех выявленных отклонений",
    ),
    FieldSpec(
        name="defects_critical",
        label="Дефекты, требующие немедленного устранения",
        type="textarea",
        group="Заключение",
        placeholder="Перечень критичных дефектов",
        description="Дефекты, влияющие на безопасность эксплуатации",
    ),
    FieldSpec(
        name="work_performed",
        label="Работы, выполненные при проверке",
        type="textarea",
        group="Заключение",
        placeholder="Продувка, подтяжка, чистка контактов",
        description="Перечень выполненных операций",
    ),
    FieldSpec(
        name="condition_assessment",
        label="Оценка технического состояния КИПиА узла",
        type="dropdown",
        group="Заключение",
        required=True,
        options=("Исправно", "Работоспособно", "Ограниченно работоспособно", "Не работоспособно"),
        description="Итоговая оценка состояния",
    ),
    FieldSpec(
        name="operation_permission",
        label="Возможность дальнейшей эксплуатации",
        type="dropdown",
        group="Заключение",
        required=True,
        options=("Допускается", "Допускается с ограничениями", "Не допускается"),
        description="Решение по результатам проверки",
    ),
    FieldSpec(
        name="repair_required",
        label="Требуется ремонт или замена",
        type="dropdown",
        group="Заключение",
        options=("Да", "Нет"),
        description="Необходимость внепланового ремонта",
    ),
    FieldSpec(
        name="repair_deadline",
        label="Срок устранения замечаний",
        type="date",
        group="Заключение",
        description="Контрольный срок по результатам проверки",
    ),
    FieldSpec(
        name="next_check_date",
        label="Дата следующей проверки",
        type="date",
        group="Заключение",
        required=True,
        description="Плановая дата следующего осмотра или ТО",
    ),
    FieldSpec(
        name="recommendation",
        label="Рекомендации по результатам проверки",
        type="textarea",
        group="Заключение",
        placeholder="Рекомендации эксплуатирующему персоналу",
        description="Мероприятия по устранению замечаний",
    ),
    FieldSpec(
        name="approver",
        label="Проверку согласовал (ФИО, должность)",
        type="text",
        group="Заключение",
        placeholder="Петров П.П., главный инженер",
        description="Согласующее лицо",
    ),
    FieldSpec(
        name="notes",
        label="Примечания",
        type="textarea",
        group="Заключение",
        placeholder="Дополнительная информация",
        description="Прочие сведения о проверке",
    ),
]


def main() -> None:
    build_template(OUTPUT, GROUPS, FIELDS)


if __name__ == "__main__":
    main()
